// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WordQuiz.Data;

#nullable disable

namespace WordQuiz.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230531124713_seedToAdmin")]
    partial class seedToAdmin
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "2",
                            Name = "Player",
                            NormalizedName = "PLAYER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "66b21145-d508-4234-9464-97ded4cf805a",
                            RoleId = "1"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("WordQuiz.Models.Topic", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Topics");

                    b.HasData(
                        new
                        {
                            Id = "a3626b87-e171-4417-af81-3d55a17a4803",
                            Description = "Learn how to address your or your partner's family at gatherings.",
                            Title = "Family"
                        },
                        new
                        {
                            Id = "5aeebccf-fab5-41f4-be5d-cac6ce23c557",
                            Description = "These words will help you cheer for your favorite team.",
                            Title = "Sports"
                        },
                        new
                        {
                            Id = "77d07ab6-c7c6-40e6-8151-b1b036b4a04b",
                            Description = "Become an Oxford level green-thumb with this vocabulary.",
                            Title = "Gardening"
                        },
                        new
                        {
                            Id = "6fb7305d-5041-4fc5-8540-08eb8ee4cb32",
                            Description = "Words related to traveling abroad.",
                            Title = "Travel"
                        },
                        new
                        {
                            Id = "02c7ee1a-dd21-4e6c-84a6-e4acb4f7b130",
                            Description = "Everything you need to know regarding fashion or about simply going shopping for clothes.",
                            Title = "Clothing"
                        },
                        new
                        {
                            Id = "90dd5f7c-c22a-4a74-8139-c94da35edc45",
                            Description = "A vocabulary aimed to help you avoid embarrassment while going out to eat.",
                            Title = "Food"
                        });
                });

            modelBuilder.Entity("WordQuiz.Models.Word", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Original")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TopicId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Translation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TopicId");

                    b.ToTable("Words");

                    b.HasData(
                        new
                        {
                            Id = "b1a2bf8d-6955-4deb-a2a0-766e91698e35",
                            Original = "Father",
                            TopicId = "a3626b87-e171-4417-af81-3d55a17a4803",
                            Translation = "Apa"
                        },
                        new
                        {
                            Id = "7f8a7a8d-2456-4fc5-a86d-97f8a0a423da",
                            Original = "Mother",
                            TopicId = "a3626b87-e171-4417-af81-3d55a17a4803",
                            Translation = "Anya"
                        },
                        new
                        {
                            Id = "5ec5cb8e-5f2e-4a5a-98f8-444df3a00b7d",
                            Original = "Aunt",
                            TopicId = "a3626b87-e171-4417-af81-3d55a17a4803",
                            Translation = "Nagynéni"
                        },
                        new
                        {
                            Id = "f667d140-1d9f-4770-844c-d690dfb38490",
                            Original = "Uncle",
                            TopicId = "a3626b87-e171-4417-af81-3d55a17a4803",
                            Translation = "Nagybácsi"
                        },
                        new
                        {
                            Id = "10ad8e75-0750-4830-8549-b8dda8735cb6",
                            Original = "Grandmother",
                            TopicId = "a3626b87-e171-4417-af81-3d55a17a4803",
                            Translation = "Nagymama"
                        },
                        new
                        {
                            Id = "567b19ef-3f56-4d6c-b4a4-a22f5bdf9b3f",
                            Original = "Grandfather",
                            TopicId = "a3626b87-e171-4417-af81-3d55a17a4803",
                            Translation = "Nagypapa"
                        },
                        new
                        {
                            Id = "dbdfa678-7810-4caa-add6-047a398a892b",
                            Original = "Grandfather",
                            TopicId = "a3626b87-e171-4417-af81-3d55a17a4803",
                            Translation = "Nagyapa"
                        },
                        new
                        {
                            Id = "d689378c-d92e-46ad-bead-5a298debc34d",
                            Original = "Mother-in-law",
                            TopicId = "a3626b87-e171-4417-af81-3d55a17a4803",
                            Translation = "Anyós"
                        },
                        new
                        {
                            Id = "3cb9a5e1-6fe0-4299-bd64-4081cda4be59",
                            Original = "Father-in-law",
                            TopicId = "a3626b87-e171-4417-af81-3d55a17a4803",
                            Translation = "Após"
                        },
                        new
                        {
                            Id = "7fbe9429-fe06-40f5-8f37-884c7650235f",
                            Original = "Son",
                            TopicId = "a3626b87-e171-4417-af81-3d55a17a4803",
                            Translation = "Fia"
                        },
                        new
                        {
                            Id = "08d84742-0237-4680-b347-854710881c46",
                            Original = "Daughter",
                            TopicId = "a3626b87-e171-4417-af81-3d55a17a4803",
                            Translation = "Lánya"
                        },
                        new
                        {
                            Id = "9083f7f7-f128-42f6-aa42-d2b413f9f9dc",
                            Original = "Brother",
                            TopicId = "a3626b87-e171-4417-af81-3d55a17a4803",
                            Translation = "Fivér"
                        },
                        new
                        {
                            Id = "78c2ffaa-26d4-4144-801a-f6abd3d4a72c",
                            Original = "Sister",
                            TopicId = "a3626b87-e171-4417-af81-3d55a17a4803",
                            Translation = "Húg"
                        },
                        new
                        {
                            Id = "d3aa30e8-6b83-4a6b-858f-9b8ee1513399",
                            Original = "Cousin",
                            TopicId = "a3626b87-e171-4417-af81-3d55a17a4803",
                            Translation = "Unokatestvér"
                        },
                        new
                        {
                            Id = "de3a348b-5475-40fa-986a-e7dc8dfe3709",
                            Original = "Nephew",
                            TopicId = "a3626b87-e171-4417-af81-3d55a17a4803",
                            Translation = "Unokaöccs"
                        },
                        new
                        {
                            Id = "d14e1367-ef02-43e4-b713-cb9114d37558",
                            Original = "Niece",
                            TopicId = "a3626b87-e171-4417-af81-3d55a17a4803",
                            Translation = "Unokahúg"
                        },
                        new
                        {
                            Id = "f3661d5b-ae28-4cc3-ac21-872db074280d",
                            Original = "Stepfather",
                            TopicId = "a3626b87-e171-4417-af81-3d55a17a4803",
                            Translation = "Mostohaapa"
                        },
                        new
                        {
                            Id = "7a536aa1-197a-49b4-aeaf-769e740eb66d",
                            Original = "Stepmother",
                            TopicId = "a3626b87-e171-4417-af81-3d55a17a4803",
                            Translation = "Mostohaanya"
                        },
                        new
                        {
                            Id = "28927ecf-37c4-4066-a491-e619254a997f",
                            Original = "Stepson",
                            TopicId = "a3626b87-e171-4417-af81-3d55a17a4803",
                            Translation = "Mostohafiú"
                        },
                        new
                        {
                            Id = "8c037be8-6e47-4445-9208-891b621ce909",
                            Original = "Stepdaughter",
                            TopicId = "a3626b87-e171-4417-af81-3d55a17a4803",
                            Translation = "Mostohalány"
                        },
                        new
                        {
                            Id = "6b9bc1bf-44bb-461f-9b6d-b11d9167ebfa",
                            Original = "Half-brother",
                            TopicId = "a3626b87-e171-4417-af81-3d55a17a4803",
                            Translation = "Félfivér"
                        },
                        new
                        {
                            Id = "11fcb03e-ec29-4e8b-8bf2-158d1ff5bc5c",
                            Original = "Half-sister",
                            TopicId = "a3626b87-e171-4417-af81-3d55a17a4803",
                            Translation = "Félnővér"
                        },
                        new
                        {
                            Id = "f6902519-18ce-49b3-9317-528d9e58cd43",
                            Original = "Sister-in-law",
                            TopicId = "a3626b87-e171-4417-af81-3d55a17a4803",
                            Translation = "Sógornő"
                        },
                        new
                        {
                            Id = "d1e31d0f-2cf8-4c00-bc5e-a1b9a2f6eba0",
                            Original = "Brother-in-law",
                            TopicId = "a3626b87-e171-4417-af81-3d55a17a4803",
                            Translation = "Sógor"
                        },
                        new
                        {
                            Id = "f7268db6-c035-496b-8566-3e767a112a08",
                            Original = "Godfather",
                            TopicId = "a3626b87-e171-4417-af81-3d55a17a4803",
                            Translation = "Keresztapa"
                        },
                        new
                        {
                            Id = "e399517e-f7c2-405b-a134-76ed3672eab9",
                            Original = "Godmother",
                            TopicId = "a3626b87-e171-4417-af81-3d55a17a4803",
                            Translation = "Keresztanya"
                        },
                        new
                        {
                            Id = "562649e7-016d-4a62-912b-9d8202e11086",
                            Original = "Great-grandmother",
                            TopicId = "a3626b87-e171-4417-af81-3d55a17a4803",
                            Translation = "Dédnagymama"
                        },
                        new
                        {
                            Id = "9fccd5d0-0039-416d-86f2-e189c25135ae",
                            Original = "Great-grandfather",
                            TopicId = "a3626b87-e171-4417-af81-3d55a17a4803",
                            Translation = "Dédnagypapa"
                        },
                        new
                        {
                            Id = "b027c7ad-4bee-4b8c-8c88-022fd13f8708",
                            Original = "Great-grandson",
                            TopicId = "a3626b87-e171-4417-af81-3d55a17a4803",
                            Translation = "Dédunoka"
                        },
                        new
                        {
                            Id = "07bbba5c-b015-4f47-9b7f-3fb7ebd66031",
                            Original = "Great-granddaughter",
                            TopicId = "a3626b87-e171-4417-af81-3d55a17a4803",
                            Translation = "Dédunoka"
                        },
                        new
                        {
                            Id = "544c6413-9bd3-443c-b0b6-025e95aa516d",
                            Original = "Team",
                            TopicId = "5aeebccf-fab5-41f4-be5d-cac6ce23c557",
                            Translation = "Csapat"
                        },
                        new
                        {
                            Id = "7b3640ad-1080-4973-8ed5-7aa64ea58d38",
                            Original = "Opponent",
                            TopicId = "5aeebccf-fab5-41f4-be5d-cac6ce23c557",
                            Translation = "Ellenfél"
                        },
                        new
                        {
                            Id = "59549e43-e629-4736-91e6-4fbb7a300fd7",
                            Original = "Stadium",
                            TopicId = "5aeebccf-fab5-41f4-be5d-cac6ce23c557",
                            Translation = "Stadion"
                        },
                        new
                        {
                            Id = "b35becc1-0300-4488-b09c-ec391e7bf610",
                            Original = "Running",
                            TopicId = "5aeebccf-fab5-41f4-be5d-cac6ce23c557",
                            Translation = "Futás"
                        },
                        new
                        {
                            Id = "20ddd5ca-c14c-4e65-b80a-e8f6b0951d14",
                            Original = "Finish",
                            TopicId = "5aeebccf-fab5-41f4-be5d-cac6ce23c557",
                            Translation = "Cél"
                        },
                        new
                        {
                            Id = "f5cc3a2d-72e9-4afe-8056-46b6d9032a28",
                            Original = "Swimming",
                            TopicId = "5aeebccf-fab5-41f4-be5d-cac6ce23c557",
                            Translation = "Úszás"
                        },
                        new
                        {
                            Id = "f1c43c7f-259e-4e0d-815e-8be7918ee111",
                            Original = "Rope",
                            TopicId = "5aeebccf-fab5-41f4-be5d-cac6ce23c557",
                            Translation = "Kötél"
                        },
                        new
                        {
                            Id = "93e354ed-1c22-4521-893e-d87e4b7b20b4",
                            Original = "Coach",
                            TopicId = "5aeebccf-fab5-41f4-be5d-cac6ce23c557",
                            Translation = "Edző"
                        },
                        new
                        {
                            Id = "b0f0ca11-d058-4184-8a13-be40a8e1f577",
                            Original = "Final",
                            TopicId = "5aeebccf-fab5-41f4-be5d-cac6ce23c557",
                            Translation = "Döntő"
                        },
                        new
                        {
                            Id = "5ff9683f-9552-4a4e-9f43-bded903163d0",
                            Original = "Basketball",
                            TopicId = "5aeebccf-fab5-41f4-be5d-cac6ce23c557",
                            Translation = "Kosárlabda"
                        },
                        new
                        {
                            Id = "e058ce51-dbd4-4720-90e5-04fbe785434e",
                            Original = "Football",
                            TopicId = "5aeebccf-fab5-41f4-be5d-cac6ce23c557",
                            Translation = "Labdarúgás"
                        },
                        new
                        {
                            Id = "e38f08d4-c323-4b96-8fce-658f98a1a96c",
                            Original = "Tennis",
                            TopicId = "5aeebccf-fab5-41f4-be5d-cac6ce23c557",
                            Translation = "Tenisz"
                        },
                        new
                        {
                            Id = "77c69054-f15f-49d1-91f8-d66b8fc9223e",
                            Original = "Baseball",
                            TopicId = "5aeebccf-fab5-41f4-be5d-cac6ce23c557",
                            Translation = "Baseball"
                        },
                        new
                        {
                            Id = "581425f2-373f-42f2-9735-77af33685a21",
                            Original = "Golf",
                            TopicId = "5aeebccf-fab5-41f4-be5d-cac6ce23c557",
                            Translation = "Golf"
                        },
                        new
                        {
                            Id = "a0130b40-240e-470c-ad26-e06b4512be75",
                            Original = "Volleyball",
                            TopicId = "5aeebccf-fab5-41f4-be5d-cac6ce23c557",
                            Translation = "Röplabda"
                        },
                        new
                        {
                            Id = "9d4e90b2-6e1d-4b35-bcca-317b2961b2e8",
                            Original = "Hockey",
                            TopicId = "5aeebccf-fab5-41f4-be5d-cac6ce23c557",
                            Translation = "Hoki"
                        },
                        new
                        {
                            Id = "21c1448b-d464-49b9-b5ac-16915494f4ed",
                            Original = "Boxing",
                            TopicId = "5aeebccf-fab5-41f4-be5d-cac6ce23c557",
                            Translation = "Boksz"
                        },
                        new
                        {
                            Id = "3e720743-ceb5-4a8d-965e-9a6d55cee80c",
                            Original = "Athletics",
                            TopicId = "5aeebccf-fab5-41f4-be5d-cac6ce23c557",
                            Translation = "Atlétika"
                        },
                        new
                        {
                            Id = "3f26cfab-914c-46e6-8c55-1fc2462312d7",
                            Original = "Cycling",
                            TopicId = "5aeebccf-fab5-41f4-be5d-cac6ce23c557",
                            Translation = "Kerékpározás"
                        },
                        new
                        {
                            Id = "adf29173-2fd9-4a85-b30e-985ccb010a30",
                            Original = "Gymnastics",
                            TopicId = "5aeebccf-fab5-41f4-be5d-cac6ce23c557",
                            Translation = "Gimnasztika"
                        },
                        new
                        {
                            Id = "87709b3f-43c7-4f23-bf3f-a9b666ca2383",
                            Original = "Skiing",
                            TopicId = "5aeebccf-fab5-41f4-be5d-cac6ce23c557",
                            Translation = "Síelés"
                        },
                        new
                        {
                            Id = "484d5a2c-1d5d-4acd-a30a-4dc6e5b293e5",
                            Original = "Wrestling",
                            TopicId = "5aeebccf-fab5-41f4-be5d-cac6ce23c557",
                            Translation = "Birkózás"
                        },
                        new
                        {
                            Id = "54a07b84-e887-4f77-b298-f946226d856f",
                            Original = "Diving",
                            TopicId = "5aeebccf-fab5-41f4-be5d-cac6ce23c557",
                            Translation = "Merülés"
                        },
                        new
                        {
                            Id = "0a292a14-2afe-4390-ab4e-88cc3b1729f8",
                            Original = "Archery",
                            TopicId = "5aeebccf-fab5-41f4-be5d-cac6ce23c557",
                            Translation = "Íjászat"
                        },
                        new
                        {
                            Id = "74c05452-35f4-4b77-b8fd-78e75dedebd4",
                            Original = "Surfing",
                            TopicId = "5aeebccf-fab5-41f4-be5d-cac6ce23c557",
                            Translation = "Szörfözés"
                        },
                        new
                        {
                            Id = "4ed8129c-1d44-44cf-aacf-b854eb496001",
                            Original = "Karate",
                            TopicId = "5aeebccf-fab5-41f4-be5d-cac6ce23c557",
                            Translation = "Karate"
                        },
                        new
                        {
                            Id = "ad133d93-8594-49fa-b8ee-3f305b28011a",
                            Original = "Gym",
                            TopicId = "5aeebccf-fab5-41f4-be5d-cac6ce23c557",
                            Translation = "Edzőterem"
                        },
                        new
                        {
                            Id = "7686521a-10f4-4a00-aa3b-079c29de3685",
                            Original = "Champion",
                            TopicId = "5aeebccf-fab5-41f4-be5d-cac6ce23c557",
                            Translation = "Bajnok"
                        },
                        new
                        {
                            Id = "0cc7d5d8-8e4d-4788-b249-58eb66bf4e21",
                            Original = "Referee",
                            TopicId = "5aeebccf-fab5-41f4-be5d-cac6ce23c557",
                            Translation = "Játékvezető"
                        },
                        new
                        {
                            Id = "3c8286c0-68f8-440b-b122-6ef11eb75326",
                            Original = "Medal",
                            TopicId = "5aeebccf-fab5-41f4-be5d-cac6ce23c557",
                            Translation = "Érem"
                        },
                        new
                        {
                            Id = "850c889f-2b76-4fe8-9337-f6e3ecaa2e57",
                            Original = "Lemon",
                            TopicId = "90dd5f7c-c22a-4a74-8139-c94da35edc45",
                            Translation = "Citrom"
                        },
                        new
                        {
                            Id = "18829a9c-df0c-4c9d-9b6d-e212a50435db",
                            Original = "Peach",
                            TopicId = "90dd5f7c-c22a-4a74-8139-c94da35edc45",
                            Translation = "Barack"
                        },
                        new
                        {
                            Id = "56ae2976-bac2-4724-9bc3-06775c0cf249",
                            Original = "Bean",
                            TopicId = "90dd5f7c-c22a-4a74-8139-c94da35edc45",
                            Translation = "Bab"
                        },
                        new
                        {
                            Id = "f9abf6aa-be2e-4e60-a444-2a68ea50ba5c",
                            Original = "Pea",
                            TopicId = "90dd5f7c-c22a-4a74-8139-c94da35edc45",
                            Translation = "Borsó"
                        },
                        new
                        {
                            Id = "83c8ac13-2ea2-4c5e-beb8-31132826d376",
                            Original = "Broccoli",
                            TopicId = "90dd5f7c-c22a-4a74-8139-c94da35edc45",
                            Translation = "Brokkoli"
                        },
                        new
                        {
                            Id = "aeed3a13-b78c-40f0-9259-2634d8811069",
                            Original = "Corn",
                            TopicId = "90dd5f7c-c22a-4a74-8139-c94da35edc45",
                            Translation = "Kukorica"
                        },
                        new
                        {
                            Id = "48eb9b21-a5f7-47a4-b5e5-947f1a80d76c",
                            Original = "Rice",
                            TopicId = "90dd5f7c-c22a-4a74-8139-c94da35edc45",
                            Translation = "Rizs"
                        },
                        new
                        {
                            Id = "db5eb7ac-6ef9-42be-9142-4a96ee432ce1",
                            Original = "Mushroom",
                            TopicId = "90dd5f7c-c22a-4a74-8139-c94da35edc45",
                            Translation = "Gomba"
                        },
                        new
                        {
                            Id = "f0343fb3-8247-4c67-b6e7-4a6c6a00aae2",
                            Original = "Carrot",
                            TopicId = "90dd5f7c-c22a-4a74-8139-c94da35edc45",
                            Translation = "Répa"
                        },
                        new
                        {
                            Id = "55ebe2cb-7f92-4c6e-8561-dfb8f245a0b6",
                            Original = "Apple",
                            TopicId = "90dd5f7c-c22a-4a74-8139-c94da35edc45",
                            Translation = "Alma"
                        },
                        new
                        {
                            Id = "21a5e4ad-041b-4ee2-bb94-997bd5b77dba",
                            Original = "Banana",
                            TopicId = "90dd5f7c-c22a-4a74-8139-c94da35edc45",
                            Translation = "Banán"
                        },
                        new
                        {
                            Id = "6ee3188d-b74e-4d5a-8e3d-24a492512d52",
                            Original = "Orange",
                            TopicId = "90dd5f7c-c22a-4a74-8139-c94da35edc45",
                            Translation = "Narancs"
                        },
                        new
                        {
                            Id = "68f47182-240c-4f07-b065-ce7545bdffa6",
                            Original = "Strawberry",
                            TopicId = "90dd5f7c-c22a-4a74-8139-c94da35edc45",
                            Translation = "Eper"
                        },
                        new
                        {
                            Id = "2598aca6-6f65-4e16-960c-e1bd54d23f38",
                            Original = "Grapes",
                            TopicId = "90dd5f7c-c22a-4a74-8139-c94da35edc45",
                            Translation = "Szőlő"
                        },
                        new
                        {
                            Id = "53496c82-ee05-408c-b8da-505e8358fd56",
                            Original = "Watermelon",
                            TopicId = "90dd5f7c-c22a-4a74-8139-c94da35edc45",
                            Translation = "Görögdinnye"
                        },
                        new
                        {
                            Id = "163c26bc-1174-4eda-8538-88ff669f7c09",
                            Original = "Tomato",
                            TopicId = "90dd5f7c-c22a-4a74-8139-c94da35edc45",
                            Translation = "Paradicsom"
                        },
                        new
                        {
                            Id = "7b8a2e4b-7484-4dd6-ad0e-a98540bd9cb4",
                            Original = "Potato",
                            TopicId = "90dd5f7c-c22a-4a74-8139-c94da35edc45",
                            Translation = "Krumpli"
                        },
                        new
                        {
                            Id = "400e55ac-0d54-43e5-a43e-d89d32e14831",
                            Original = "Cucumber",
                            TopicId = "90dd5f7c-c22a-4a74-8139-c94da35edc45",
                            Translation = "Uborka"
                        },
                        new
                        {
                            Id = "db9f0e8c-fc14-4b1f-a1bd-c0ec946d9546",
                            Original = "Cheese",
                            TopicId = "90dd5f7c-c22a-4a74-8139-c94da35edc45",
                            Translation = "Sajt"
                        },
                        new
                        {
                            Id = "3328a458-d709-4076-b90f-11a96fedf070",
                            Original = "Bread",
                            TopicId = "90dd5f7c-c22a-4a74-8139-c94da35edc45",
                            Translation = "Kenyér"
                        },
                        new
                        {
                            Id = "9b514f4a-9b53-403d-9fe0-f4b61966a9f4",
                            Original = "Meat",
                            TopicId = "90dd5f7c-c22a-4a74-8139-c94da35edc45",
                            Translation = "Hús"
                        },
                        new
                        {
                            Id = "79447893-c38b-4d5a-b62d-79f3f4658235",
                            Original = "Fish",
                            TopicId = "90dd5f7c-c22a-4a74-8139-c94da35edc45",
                            Translation = "Hal"
                        },
                        new
                        {
                            Id = "076a8a96-e01c-4a10-af9d-19ee31a123b2",
                            Original = "Egg",
                            TopicId = "90dd5f7c-c22a-4a74-8139-c94da35edc45",
                            Translation = "Tojás"
                        },
                        new
                        {
                            Id = "29f9dfbb-2a7e-4045-9138-eebd4998a42e",
                            Original = "Butter",
                            TopicId = "90dd5f7c-c22a-4a74-8139-c94da35edc45",
                            Translation = "Vaj"
                        },
                        new
                        {
                            Id = "2616e0f4-21ae-457a-b9a6-5aa251d88260",
                            Original = "Sugar",
                            TopicId = "90dd5f7c-c22a-4a74-8139-c94da35edc45",
                            Translation = "Cukor"
                        },
                        new
                        {
                            Id = "6017f634-09ff-4c86-9530-983666eca343",
                            Original = "Salt",
                            TopicId = "90dd5f7c-c22a-4a74-8139-c94da35edc45",
                            Translation = "Só"
                        },
                        new
                        {
                            Id = "d837b78d-ced4-4eb2-8079-ab278bdc64ab",
                            Original = "Pepper",
                            TopicId = "90dd5f7c-c22a-4a74-8139-c94da35edc45",
                            Translation = "Bors"
                        },
                        new
                        {
                            Id = "eac74ed6-7856-4d7f-ae7d-96a11603f8de",
                            Original = "Honey",
                            TopicId = "90dd5f7c-c22a-4a74-8139-c94da35edc45",
                            Translation = "Méz"
                        },
                        new
                        {
                            Id = "b4f16b33-0f8d-4aa9-bbc8-df990f46959f",
                            Original = "Ice cream",
                            TopicId = "90dd5f7c-c22a-4a74-8139-c94da35edc45",
                            Translation = "Fagylalt"
                        },
                        new
                        {
                            Id = "0d88145a-b2ef-431a-8f13-74483f928b7b",
                            Original = "Suitcase",
                            TopicId = "6fb7305d-5041-4fc5-8540-08eb8ee4cb32",
                            Translation = "Bőrönd"
                        },
                        new
                        {
                            Id = "da2a21f2-7a0d-4c72-b938-ea1dbf175992",
                            Original = "Ferry",
                            TopicId = "6fb7305d-5041-4fc5-8540-08eb8ee4cb32",
                            Translation = "Komp"
                        },
                        new
                        {
                            Id = "85d4b5e3-0c4e-4197-91c3-2ffd47dad43b",
                            Original = "Airport",
                            TopicId = "6fb7305d-5041-4fc5-8540-08eb8ee4cb32",
                            Translation = "Reptér"
                        },
                        new
                        {
                            Id = "ee0848d1-eca6-42e6-929d-f0f0a92f96f8",
                            Original = "Travel agency",
                            TopicId = "6fb7305d-5041-4fc5-8540-08eb8ee4cb32",
                            Translation = "Utazási iroda"
                        },
                        new
                        {
                            Id = "bb036f1c-6544-4e11-a330-c8f4d5a6f0d1",
                            Original = "Service",
                            TopicId = "6fb7305d-5041-4fc5-8540-08eb8ee4cb32",
                            Translation = "Szolgáltatás"
                        },
                        new
                        {
                            Id = "549f9a77-1e47-4cc0-8929-562792650287",
                            Original = "Reception",
                            TopicId = "6fb7305d-5041-4fc5-8540-08eb8ee4cb32",
                            Translation = "Recepció"
                        },
                        new
                        {
                            Id = "d44b847b-b6eb-40f8-9728-cd400e69ad19",
                            Original = "Delay",
                            TopicId = "6fb7305d-5041-4fc5-8540-08eb8ee4cb32",
                            Translation = "Késés"
                        },
                        new
                        {
                            Id = "633d23d3-2020-4070-bd6c-a8d1d0586a73",
                            Original = "Airline",
                            TopicId = "6fb7305d-5041-4fc5-8540-08eb8ee4cb32",
                            Translation = "Légitársaság"
                        },
                        new
                        {
                            Id = "59cfe750-391f-4022-a990-976e4ed34107",
                            Original = "Passport",
                            TopicId = "6fb7305d-5041-4fc5-8540-08eb8ee4cb32",
                            Translation = "Útlevél"
                        },
                        new
                        {
                            Id = "07a80b0e-18a3-4136-b562-5a798229b217",
                            Original = "Hotel",
                            TopicId = "6fb7305d-5041-4fc5-8540-08eb8ee4cb32",
                            Translation = "Szálloda"
                        },
                        new
                        {
                            Id = "03072284-06b8-4d8a-a4f1-1edb80c13c8f",
                            Original = "Train",
                            TopicId = "6fb7305d-5041-4fc5-8540-08eb8ee4cb32",
                            Translation = "Vonat"
                        },
                        new
                        {
                            Id = "a291e160-8b80-49cb-9ab6-c2b2be385b62",
                            Original = "Bus",
                            TopicId = "6fb7305d-5041-4fc5-8540-08eb8ee4cb32",
                            Translation = "Busz"
                        },
                        new
                        {
                            Id = "69151328-0c92-4219-a744-b94132196be1",
                            Original = "Taxi",
                            TopicId = "6fb7305d-5041-4fc5-8540-08eb8ee4cb32",
                            Translation = "Taxi"
                        },
                        new
                        {
                            Id = "f134e36f-fbf6-4e74-b70a-c5fdc4134093",
                            Original = "Car",
                            TopicId = "6fb7305d-5041-4fc5-8540-08eb8ee4cb32",
                            Translation = "Autó"
                        },
                        new
                        {
                            Id = "47874879-d0bc-4e7c-88d0-b6b175f863a5",
                            Original = "Ticket",
                            TopicId = "6fb7305d-5041-4fc5-8540-08eb8ee4cb32",
                            Translation = "Jegy"
                        },
                        new
                        {
                            Id = "099b7383-327f-4a4b-8d13-df8388c8293d",
                            Original = "Boarding pass",
                            TopicId = "6fb7305d-5041-4fc5-8540-08eb8ee4cb32",
                            Translation = "Beszállókártya"
                        },
                        new
                        {
                            Id = "03088e60-e337-401b-876a-04011be6a3b6",
                            Original = "Luggage",
                            TopicId = "6fb7305d-5041-4fc5-8540-08eb8ee4cb32",
                            Translation = "Csomag"
                        },
                        new
                        {
                            Id = "ad26f5ef-a81b-459a-8372-7255976a8fb9",
                            Original = "Destination",
                            TopicId = "6fb7305d-5041-4fc5-8540-08eb8ee4cb32",
                            Translation = "Célállomás"
                        },
                        new
                        {
                            Id = "48ccd606-1734-46f6-8119-6da11395af85",
                            Original = "Tourist",
                            TopicId = "6fb7305d-5041-4fc5-8540-08eb8ee4cb32",
                            Translation = "Turista"
                        },
                        new
                        {
                            Id = "df1a103e-074a-43df-9187-19b481769e48",
                            Original = "Guide",
                            TopicId = "6fb7305d-5041-4fc5-8540-08eb8ee4cb32",
                            Translation = "Idegenvezető"
                        },
                        new
                        {
                            Id = "df57ebfc-3c25-49a7-ab3d-95a93a5d6701",
                            Original = "Map",
                            TopicId = "6fb7305d-5041-4fc5-8540-08eb8ee4cb32",
                            Translation = "Térkép"
                        },
                        new
                        {
                            Id = "6d5eda65-2c2a-4459-a7de-1e9b27254cf4",
                            Original = "Beach",
                            TopicId = "6fb7305d-5041-4fc5-8540-08eb8ee4cb32",
                            Translation = "Strand"
                        },
                        new
                        {
                            Id = "c4ea547b-985d-44bd-9100-82fdb4bcc53f",
                            Original = "Mountain",
                            TopicId = "6fb7305d-5041-4fc5-8540-08eb8ee4cb32",
                            Translation = "Hegy"
                        },
                        new
                        {
                            Id = "bc99bbc6-fc36-4f31-90d9-9045e51f7f4a",
                            Original = "Lake",
                            TopicId = "6fb7305d-5041-4fc5-8540-08eb8ee4cb32",
                            Translation = "Tó"
                        },
                        new
                        {
                            Id = "2ba21e05-f00b-44ff-90b7-4822c7dacc73",
                            Original = "Island",
                            TopicId = "6fb7305d-5041-4fc5-8540-08eb8ee4cb32",
                            Translation = "Sziget"
                        },
                        new
                        {
                            Id = "4c400c4c-79f1-438b-99ac-736e880fdc04",
                            Original = "Sightseeing",
                            TopicId = "6fb7305d-5041-4fc5-8540-08eb8ee4cb32",
                            Translation = "Városnézés"
                        },
                        new
                        {
                            Id = "bd81f085-594f-4235-a4de-4b760006d084",
                            Original = "Currency",
                            TopicId = "6fb7305d-5041-4fc5-8540-08eb8ee4cb32",
                            Translation = "Pénznem"
                        },
                        new
                        {
                            Id = "c09074ad-1fbd-4a8c-9a5e-ac9db88ba3d9",
                            Original = "Souvenir",
                            TopicId = "6fb7305d-5041-4fc5-8540-08eb8ee4cb32",
                            Translation = "Szouvenir"
                        },
                        new
                        {
                            Id = "0fd174c9-6a98-4059-b722-280e91ac9b7c",
                            Original = "Adventure",
                            TopicId = "6fb7305d-5041-4fc5-8540-08eb8ee4cb32",
                            Translation = "Kaland"
                        },
                        new
                        {
                            Id = "6a8b7e15-6436-4d63-bbcc-e97d153449d1",
                            Original = "Dress",
                            TopicId = "02c7ee1a-dd21-4e6c-84a6-e4acb4f7b130",
                            Translation = "Ruha"
                        },
                        new
                        {
                            Id = "0e84f7e1-afa8-4331-993b-7ab7d250740b",
                            Original = "Fashionable",
                            TopicId = "02c7ee1a-dd21-4e6c-84a6-e4acb4f7b130",
                            Translation = "Divatos"
                        },
                        new
                        {
                            Id = "7595ad6f-0f5f-4d75-a3e3-b67772f1358c",
                            Original = "Cap",
                            TopicId = "02c7ee1a-dd21-4e6c-84a6-e4acb4f7b130",
                            Translation = "Sapka"
                        },
                        new
                        {
                            Id = "b4ddce81-e5de-490d-bf68-4014b6bc4763",
                            Original = "Bathrobe",
                            TopicId = "02c7ee1a-dd21-4e6c-84a6-e4acb4f7b130",
                            Translation = "Fürdőköpeny"
                        },
                        new
                        {
                            Id = "eaae48e3-47a5-4625-a996-cf11ea398446",
                            Original = "Belt",
                            TopicId = "02c7ee1a-dd21-4e6c-84a6-e4acb4f7b130",
                            Translation = "Öv"
                        },
                        new
                        {
                            Id = "76c94983-7695-4c5e-8e72-7f406b31411d",
                            Original = "Jeans",
                            TopicId = "02c7ee1a-dd21-4e6c-84a6-e4acb4f7b130",
                            Translation = "Farmernadrág"
                        },
                        new
                        {
                            Id = "0c68b910-9dbe-46ca-83d5-fbfbb199fd3c",
                            Original = "Boots",
                            TopicId = "02c7ee1a-dd21-4e6c-84a6-e4acb4f7b130",
                            Translation = "Csizma"
                        },
                        new
                        {
                            Id = "c48dca60-73c8-4d40-a48b-8d1b3248d7b8",
                            Original = "Bracelet",
                            TopicId = "02c7ee1a-dd21-4e6c-84a6-e4acb4f7b130",
                            Translation = "Karkötő"
                        },
                        new
                        {
                            Id = "3353fdc6-e153-425c-aec8-f762f3e18750",
                            Original = "Coat",
                            TopicId = "02c7ee1a-dd21-4e6c-84a6-e4acb4f7b130",
                            Translation = "Kabát"
                        },
                        new
                        {
                            Id = "53c1322b-a3e1-4f34-97a0-f64f24a68b6f",
                            Original = "Shirt",
                            TopicId = "02c7ee1a-dd21-4e6c-84a6-e4acb4f7b130",
                            Translation = "Ing"
                        },
                        new
                        {
                            Id = "0ce09eb7-9b1a-4ab9-ae29-dd2a5445fd36",
                            Original = "T-shirt",
                            TopicId = "02c7ee1a-dd21-4e6c-84a6-e4acb4f7b130",
                            Translation = "Póló"
                        },
                        new
                        {
                            Id = "c26ebee5-a824-444b-8478-ffe7b87a90c4",
                            Original = "Skirt",
                            TopicId = "02c7ee1a-dd21-4e6c-84a6-e4acb4f7b130",
                            Translation = "Szoknya"
                        },
                        new
                        {
                            Id = "609ca916-3b90-4313-b9e6-5514bfef7346",
                            Original = "Trousers",
                            TopicId = "02c7ee1a-dd21-4e6c-84a6-e4acb4f7b130",
                            Translation = "Nadrág"
                        },
                        new
                        {
                            Id = "d76bbfff-a97f-4511-83d4-3fa31e4d7d6f",
                            Original = "Sweater",
                            TopicId = "02c7ee1a-dd21-4e6c-84a6-e4acb4f7b130",
                            Translation = "Pulóver"
                        },
                        new
                        {
                            Id = "ebdd57b2-94b6-4c5e-8a8d-90f5ca2e566a",
                            Original = "Jacket",
                            TopicId = "02c7ee1a-dd21-4e6c-84a6-e4acb4f7b130",
                            Translation = "Kabát"
                        },
                        new
                        {
                            Id = "34d0b1af-b46d-4dcd-ad5c-897cb2fd49ea",
                            Original = "Socks",
                            TopicId = "02c7ee1a-dd21-4e6c-84a6-e4acb4f7b130",
                            Translation = "Zokni"
                        },
                        new
                        {
                            Id = "6928d1e0-336d-4533-b869-068b0f240e70",
                            Original = "Shoes",
                            TopicId = "02c7ee1a-dd21-4e6c-84a6-e4acb4f7b130",
                            Translation = "Cipő"
                        },
                        new
                        {
                            Id = "bc2fd609-6459-4a2a-91a7-e14fd906b9ea",
                            Original = "Hat",
                            TopicId = "02c7ee1a-dd21-4e6c-84a6-e4acb4f7b130",
                            Translation = "Kalap"
                        },
                        new
                        {
                            Id = "dcade8da-26ac-4dc2-93cd-16cc19f98d08",
                            Original = "Gloves",
                            TopicId = "02c7ee1a-dd21-4e6c-84a6-e4acb4f7b130",
                            Translation = "Kesztyű"
                        },
                        new
                        {
                            Id = "03d3d594-d66e-4262-80e2-3d5db09061d4",
                            Original = "Scarf",
                            TopicId = "02c7ee1a-dd21-4e6c-84a6-e4acb4f7b130",
                            Translation = "Sál"
                        },
                        new
                        {
                            Id = "39e2b4c8-c450-4eb9-9726-b3eb477b6baf",
                            Original = "Underwear",
                            TopicId = "02c7ee1a-dd21-4e6c-84a6-e4acb4f7b130",
                            Translation = "Alsónemű"
                        },
                        new
                        {
                            Id = "204c6e83-6195-44a8-8bc8-66394bf0c7a8",
                            Original = "Pajamas",
                            TopicId = "02c7ee1a-dd21-4e6c-84a6-e4acb4f7b130",
                            Translation = "Pizsama"
                        },
                        new
                        {
                            Id = "daf243b4-0749-412f-98c7-57ba58e5616e",
                            Original = "Swimsuit",
                            TopicId = "02c7ee1a-dd21-4e6c-84a6-e4acb4f7b130",
                            Translation = "Fürdőruha"
                        },
                        new
                        {
                            Id = "c00306a9-3fad-47fc-80b8-8ac3521e9856",
                            Original = "Bikini",
                            TopicId = "02c7ee1a-dd21-4e6c-84a6-e4acb4f7b130",
                            Translation = "Bikini"
                        },
                        new
                        {
                            Id = "6728addb-59e7-4532-8987-17fa3c52817f",
                            Original = "Tie",
                            TopicId = "02c7ee1a-dd21-4e6c-84a6-e4acb4f7b130",
                            Translation = "Nyakkendő"
                        },
                        new
                        {
                            Id = "094cf5b8-d5d4-4350-b8e3-f56400308a33",
                            Original = "Handbag",
                            TopicId = "02c7ee1a-dd21-4e6c-84a6-e4acb4f7b130",
                            Translation = "Kézitáska"
                        },
                        new
                        {
                            Id = "26a49f34-4f0c-4f8c-9fc6-2787e13e9b3e",
                            Original = "Wallet",
                            TopicId = "02c7ee1a-dd21-4e6c-84a6-e4acb4f7b130",
                            Translation = "Pénztárca"
                        },
                        new
                        {
                            Id = "31b20862-21a9-45d1-8120-7b5f39437b45",
                            Original = "Watch",
                            TopicId = "02c7ee1a-dd21-4e6c-84a6-e4acb4f7b130",
                            Translation = "Óra"
                        },
                        new
                        {
                            Id = "ee7a83eb-298b-4f2a-9379-247ef8471c5c",
                            Original = "Flowerpot",
                            TopicId = "77d07ab6-c7c6-40e6-8151-b1b036b4a04b",
                            Translation = "Virágcserép"
                        },
                        new
                        {
                            Id = "320905d1-e42d-410d-96d5-be6618e9ee0f",
                            Original = "Raking",
                            TopicId = "77d07ab6-c7c6-40e6-8151-b1b036b4a04b",
                            Translation = "Gereblyézés"
                        },
                        new
                        {
                            Id = "7f643b24-02fc-4820-96b7-ae53a11b3fde",
                            Original = "Seed",
                            TopicId = "77d07ab6-c7c6-40e6-8151-b1b036b4a04b",
                            Translation = "Mag"
                        },
                        new
                        {
                            Id = "7aa6442b-1cf4-4399-8d55-8a3f9f2d41fe",
                            Original = "Soil",
                            TopicId = "77d07ab6-c7c6-40e6-8151-b1b036b4a04b",
                            Translation = "Termőföld"
                        },
                        new
                        {
                            Id = "de37137c-a9dc-4f54-b3d7-3feaa6d20f48",
                            Original = "Hole",
                            TopicId = "77d07ab6-c7c6-40e6-8151-b1b036b4a04b",
                            Translation = "Lyuk"
                        },
                        new
                        {
                            Id = "9b53d34d-c160-4c88-86a2-0679f1a87ac6",
                            Original = "Dirt",
                            TopicId = "77d07ab6-c7c6-40e6-8151-b1b036b4a04b",
                            Translation = "Föld"
                        },
                        new
                        {
                            Id = "ba390d74-b766-41bb-9837-99ce39e8dbd2",
                            Original = "Lawn mowing",
                            TopicId = "77d07ab6-c7c6-40e6-8151-b1b036b4a04b",
                            Translation = "Fűnyírás"
                        },
                        new
                        {
                            Id = "f6fcb6cc-5b22-4f97-8899-aaff152ff8fc",
                            Original = "Spade",
                            TopicId = "77d07ab6-c7c6-40e6-8151-b1b036b4a04b",
                            Translation = "Ásó"
                        },
                        new
                        {
                            Id = "bc1d803a-1581-4b01-ac92-413c21109fc9",
                            Original = "Wheelbarrow",
                            TopicId = "77d07ab6-c7c6-40e6-8151-b1b036b4a04b",
                            Translation = "Talicska"
                        },
                        new
                        {
                            Id = "fdf1e53d-67d9-4dfd-a17e-3cd5efa296ce",
                            Original = "Watering can",
                            TopicId = "77d07ab6-c7c6-40e6-8151-b1b036b4a04b",
                            Translation = "Öntözőkanna"
                        },
                        new
                        {
                            Id = "4486bae2-a628-4cfd-a0b1-86e103d02855",
                            Original = "Garden hose",
                            TopicId = "77d07ab6-c7c6-40e6-8151-b1b036b4a04b",
                            Translation = "Kerti tömlő"
                        },
                        new
                        {
                            Id = "c38ce348-80aa-4941-bfe3-71afdf453ab7",
                            Original = "Pruning shears",
                            TopicId = "77d07ab6-c7c6-40e6-8151-b1b036b4a04b",
                            Translation = "Metszőolló"
                        },
                        new
                        {
                            Id = "1203b806-0bd8-4367-83f6-ffb0f24bdd99",
                            Original = "Garden gloves",
                            TopicId = "77d07ab6-c7c6-40e6-8151-b1b036b4a04b",
                            Translation = "Kerti kesztyű"
                        },
                        new
                        {
                            Id = "d07159cb-3c65-4c28-9423-9c39861b1e7c",
                            Original = "Shovel",
                            TopicId = "77d07ab6-c7c6-40e6-8151-b1b036b4a04b",
                            Translation = "Ásó"
                        },
                        new
                        {
                            Id = "b93e2950-1a57-4377-b6f7-ac1225a97d4d",
                            Original = "Rake",
                            TopicId = "77d07ab6-c7c6-40e6-8151-b1b036b4a04b",
                            Translation = "Gereblye"
                        },
                        new
                        {
                            Id = "5dab28cb-aa72-477e-9271-e3bb8c5277ce",
                            Original = "Garden fork",
                            TopicId = "77d07ab6-c7c6-40e6-8151-b1b036b4a04b",
                            Translation = "Kerti villa"
                        },
                        new
                        {
                            Id = "ca458f72-74f8-4162-aff9-2c20a3efbd6f",
                            Original = "Pruner",
                            TopicId = "77d07ab6-c7c6-40e6-8151-b1b036b4a04b",
                            Translation = "Metszőolló"
                        },
                        new
                        {
                            Id = "cd2ee3b1-8335-4d93-ac3b-036d2bc0dcad",
                            Original = "Garden trowel",
                            TopicId = "77d07ab6-c7c6-40e6-8151-b1b036b4a04b",
                            Translation = "Kerti talicska"
                        },
                        new
                        {
                            Id = "b51d8c23-31fe-4e28-866d-a250092ce012",
                            Original = "Garden hoe",
                            TopicId = "77d07ab6-c7c6-40e6-8151-b1b036b4a04b",
                            Translation = "Kerti kapa"
                        },
                        new
                        {
                            Id = "2ce46178-ffe6-4c40-866a-e153f5a1ec17",
                            Original = "Garden rake",
                            TopicId = "77d07ab6-c7c6-40e6-8151-b1b036b4a04b",
                            Translation = "Kerti gereblye"
                        },
                        new
                        {
                            Id = "4543a8ba-0d70-43f5-a275-86bf70a6e19f",
                            Original = "Garden sprayer",
                            TopicId = "77d07ab6-c7c6-40e6-8151-b1b036b4a04b",
                            Translation = "Kerti permetező"
                        },
                        new
                        {
                            Id = "52ea22a7-adeb-40bb-831e-28aca7d0f525",
                            Original = "Garden cart",
                            TopicId = "77d07ab6-c7c6-40e6-8151-b1b036b4a04b",
                            Translation = "Kerti szekér"
                        },
                        new
                        {
                            Id = "9dcad437-c1b3-49a0-a19c-5860d822b501",
                            Original = "Garden stake",
                            TopicId = "77d07ab6-c7c6-40e6-8151-b1b036b4a04b",
                            Translation = "Kerti tüske"
                        },
                        new
                        {
                            Id = "dc5910be-6edf-4f99-a323-9f134dca61db",
                            Original = "Garden trellis",
                            TopicId = "77d07ab6-c7c6-40e6-8151-b1b036b4a04b",
                            Translation = "Kerti rács"
                        },
                        new
                        {
                            Id = "ddb43bce-aaa2-4bd8-b70f-d45e50303a38",
                            Original = "Plant pot",
                            TopicId = "77d07ab6-c7c6-40e6-8151-b1b036b4a04b",
                            Translation = "Növényi edény"
                        },
                        new
                        {
                            Id = "029f88f6-076d-46e3-bbd1-6e264b14bb41",
                            Original = "Compost bin",
                            TopicId = "77d07ab6-c7c6-40e6-8151-b1b036b4a04b",
                            Translation = "Komposztáló"
                        },
                        new
                        {
                            Id = "d53f7e60-9d0b-4784-bde1-1e18ac2a96ae",
                            Original = "Garden bench",
                            TopicId = "77d07ab6-c7c6-40e6-8151-b1b036b4a04b",
                            Translation = "Kerti pad"
                        },
                        new
                        {
                            Id = "7d2f6039-3331-4f0c-9889-bcce2df21634",
                            Original = "Garden gnome",
                            TopicId = "77d07ab6-c7c6-40e6-8151-b1b036b4a04b",
                            Translation = "Kerti törpe"
                        });
                });

            modelBuilder.Entity("WordQuiz.Models.WordStatistic", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PlayerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<string>("WordId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("WordId");

                    b.ToTable("WordStatistics");
                });

            modelBuilder.Entity("WordQuiz.Models.Player", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Player");

                    b.HasData(
                        new
                        {
                            Id = "66b21145-d508-4234-9464-97ded4cf805a",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d631b54b-4240-45c4-bde6-c2f24ac0d489",
                            Email = "seedplayer@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedUserName = "SEEDPLAYER@gmail.com",
                            PasswordHash = "AQAAAAEAACcQAAAAELcExb9V5J4E19rWmBPjjHbDN1TUAx1U2s1tet4Z5oR7HSb7K5a14nl38CNgrqZlTA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a74cc864-3b8f-49ba-8ed4-15129d8136ca",
                            TwoFactorEnabled = false,
                            UserName = "seedplayer@gmail.com",
                            PlayerName = "SeedPlayer"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WordQuiz.Models.Word", b =>
                {
                    b.HasOne("WordQuiz.Models.Topic", "Topic")
                        .WithMany("Words")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("WordQuiz.Models.WordStatistic", b =>
                {
                    b.HasOne("WordQuiz.Models.Player", "Player")
                        .WithMany("WordStatistics")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WordQuiz.Models.Word", "Word")
                        .WithMany()
                        .HasForeignKey("WordId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Word");
                });

            modelBuilder.Entity("WordQuiz.Models.Topic", b =>
                {
                    b.Navigation("Words");
                });

            modelBuilder.Entity("WordQuiz.Models.Player", b =>
                {
                    b.Navigation("WordStatistics");
                });
#pragma warning restore 612, 618
        }
    }
}
