// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WordQuiz.Data;

#nullable disable

namespace WordQuiz.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230531120434__seedWords")]
    partial class _seedWords
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "2",
                            Name = "Player",
                            NormalizedName = "PLAYER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("WordQuiz.Models.Topic", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Topics");

                    b.HasData(
                        new
                        {
                            Id = "d717aa31-70c0-41b5-8632-3472e63711f2",
                            Description = "Learn how to address your or your partner's family at gatherings.",
                            Title = "Family"
                        },
                        new
                        {
                            Id = "229f3ebe-81a8-4b8e-a8b6-b82bdbaa723a",
                            Description = "These words will help you cheer for your favorite team.",
                            Title = "Sports"
                        },
                        new
                        {
                            Id = "b7e85018-1d81-4e39-b50f-e213f95579d2",
                            Description = "Become an Oxford level green-thumb with this vocabulary.",
                            Title = "Gardening"
                        },
                        new
                        {
                            Id = "058be191-523d-4501-b6f6-3bf57263d568",
                            Description = "Words related to traveling abroad.",
                            Title = "Travel"
                        },
                        new
                        {
                            Id = "8f3b5b7d-b2b5-44e5-bf9d-5cf765efda15",
                            Description = "Everything you need to know regarding fashion or about simply going shopping for clothes.",
                            Title = "Clothing"
                        },
                        new
                        {
                            Id = "211b3d26-fb6a-438e-af53-d8124e9c0911",
                            Description = "A vocabulary aimed to help you avoid embarrassment while going out to eat.",
                            Title = "Food"
                        });
                });

            modelBuilder.Entity("WordQuiz.Models.Word", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Original")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TopicId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Translation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TopicId");

                    b.ToTable("Words");

                    b.HasData(
                        new
                        {
                            Id = "2c4c52ab-1c12-40d5-b576-0711f3309e05",
                            Original = "Father",
                            TopicId = "d717aa31-70c0-41b5-8632-3472e63711f2",
                            Translation = "Apa"
                        },
                        new
                        {
                            Id = "985cdc76-2604-45dc-9617-d88d19cc41ce",
                            Original = "Mother",
                            TopicId = "d717aa31-70c0-41b5-8632-3472e63711f2",
                            Translation = "Anya"
                        },
                        new
                        {
                            Id = "41e672b0-b77a-4677-a380-6f13193dec3d",
                            Original = "Aunt",
                            TopicId = "d717aa31-70c0-41b5-8632-3472e63711f2",
                            Translation = "Nagynéni"
                        },
                        new
                        {
                            Id = "85e1e83a-d0a3-4c7b-abc3-2e06e92cf04a",
                            Original = "Uncle",
                            TopicId = "d717aa31-70c0-41b5-8632-3472e63711f2",
                            Translation = "Nagybácsi"
                        },
                        new
                        {
                            Id = "4d30dae0-ed68-45c4-a693-84fce6668524",
                            Original = "Grandmother",
                            TopicId = "d717aa31-70c0-41b5-8632-3472e63711f2",
                            Translation = "Nagymama"
                        },
                        new
                        {
                            Id = "4a957b42-d853-48b3-822a-c01f153995ac",
                            Original = "Grandfather",
                            TopicId = "d717aa31-70c0-41b5-8632-3472e63711f2",
                            Translation = "Nagypapa"
                        },
                        new
                        {
                            Id = "cc81df8a-e5ce-4352-8add-5245711b4335",
                            Original = "Grandfather",
                            TopicId = "d717aa31-70c0-41b5-8632-3472e63711f2",
                            Translation = "Nagyapa"
                        },
                        new
                        {
                            Id = "9c1936e5-8c20-411f-8211-b32708420f20",
                            Original = "Mother-in-law",
                            TopicId = "d717aa31-70c0-41b5-8632-3472e63711f2",
                            Translation = "Anyós"
                        },
                        new
                        {
                            Id = "6e966891-5ba6-4861-8feb-22dcb9dc4288",
                            Original = "Father-in-law",
                            TopicId = "d717aa31-70c0-41b5-8632-3472e63711f2",
                            Translation = "Após"
                        },
                        new
                        {
                            Id = "2f4dfc8c-b64b-4eaa-b1ed-60ec5099fa2e",
                            Original = "Son",
                            TopicId = "d717aa31-70c0-41b5-8632-3472e63711f2",
                            Translation = "Fia"
                        },
                        new
                        {
                            Id = "fe0d968c-c2af-4be4-b423-aded07173f1b",
                            Original = "Daughter",
                            TopicId = "d717aa31-70c0-41b5-8632-3472e63711f2",
                            Translation = "Lánya"
                        },
                        new
                        {
                            Id = "9f189fb7-3857-408c-b145-fee4be37c9de",
                            Original = "Brother",
                            TopicId = "d717aa31-70c0-41b5-8632-3472e63711f2",
                            Translation = "Fivér"
                        },
                        new
                        {
                            Id = "18b28cb6-f0ca-4e31-b6a4-36575e024814",
                            Original = "Sister",
                            TopicId = "d717aa31-70c0-41b5-8632-3472e63711f2",
                            Translation = "Húg"
                        },
                        new
                        {
                            Id = "e9ec5284-b040-4b23-8e2c-12673e1966cc",
                            Original = "Cousin",
                            TopicId = "d717aa31-70c0-41b5-8632-3472e63711f2",
                            Translation = "Unokatestvér"
                        },
                        new
                        {
                            Id = "de64811e-5f1e-47bb-92dc-602e5debc1ca",
                            Original = "Nephew",
                            TopicId = "d717aa31-70c0-41b5-8632-3472e63711f2",
                            Translation = "Unokaöccs"
                        },
                        new
                        {
                            Id = "c5783716-9815-43fb-9ea5-166765f28a3c",
                            Original = "Niece",
                            TopicId = "d717aa31-70c0-41b5-8632-3472e63711f2",
                            Translation = "Unokahúg"
                        },
                        new
                        {
                            Id = "52c9328a-e4d7-423f-bc5f-6a3bca53e904",
                            Original = "Stepfather",
                            TopicId = "d717aa31-70c0-41b5-8632-3472e63711f2",
                            Translation = "Mostohaapa"
                        },
                        new
                        {
                            Id = "412863f4-b751-44f4-93e3-7e1aac992759",
                            Original = "Stepmother",
                            TopicId = "d717aa31-70c0-41b5-8632-3472e63711f2",
                            Translation = "Mostohaanya"
                        },
                        new
                        {
                            Id = "a98bb43b-9d20-479f-ba26-cf38fa6d4934",
                            Original = "Stepson",
                            TopicId = "d717aa31-70c0-41b5-8632-3472e63711f2",
                            Translation = "Mostohafiú"
                        },
                        new
                        {
                            Id = "a1a94b03-13e4-4941-9069-0fb16ebf4a25",
                            Original = "Stepdaughter",
                            TopicId = "d717aa31-70c0-41b5-8632-3472e63711f2",
                            Translation = "Mostohalány"
                        },
                        new
                        {
                            Id = "94c570f6-0e57-4e74-9bed-436cbb89d912",
                            Original = "Half-brother",
                            TopicId = "d717aa31-70c0-41b5-8632-3472e63711f2",
                            Translation = "Félfivér"
                        },
                        new
                        {
                            Id = "8132b99e-9acf-446d-b2e1-7a61a3b278dd",
                            Original = "Half-sister",
                            TopicId = "d717aa31-70c0-41b5-8632-3472e63711f2",
                            Translation = "Félnővér"
                        },
                        new
                        {
                            Id = "0af3c16b-2cb3-4276-8a99-bfa4c8125cfa",
                            Original = "Sister-in-law",
                            TopicId = "d717aa31-70c0-41b5-8632-3472e63711f2",
                            Translation = "Sógornő"
                        },
                        new
                        {
                            Id = "f60fe7ca-5d83-4298-901c-544995511f33",
                            Original = "Brother-in-law",
                            TopicId = "d717aa31-70c0-41b5-8632-3472e63711f2",
                            Translation = "Sógor"
                        },
                        new
                        {
                            Id = "186a0e51-d104-4450-b667-1e61cb5d3656",
                            Original = "Godfather",
                            TopicId = "d717aa31-70c0-41b5-8632-3472e63711f2",
                            Translation = "Keresztapa"
                        },
                        new
                        {
                            Id = "af028216-4bf5-43cc-b2c1-7c508c768a0d",
                            Original = "Godmother",
                            TopicId = "d717aa31-70c0-41b5-8632-3472e63711f2",
                            Translation = "Keresztanya"
                        },
                        new
                        {
                            Id = "27d7a53b-cbb1-4f60-80f6-9a586f0d5526",
                            Original = "Great-grandmother",
                            TopicId = "d717aa31-70c0-41b5-8632-3472e63711f2",
                            Translation = "Dédnagymama"
                        },
                        new
                        {
                            Id = "787d3919-16de-4c7d-9724-8d187eefa230",
                            Original = "Great-grandfather",
                            TopicId = "d717aa31-70c0-41b5-8632-3472e63711f2",
                            Translation = "Dédnagypapa"
                        },
                        new
                        {
                            Id = "fcb03109-59d4-4f73-b903-1a52cb985496",
                            Original = "Great-grandson",
                            TopicId = "d717aa31-70c0-41b5-8632-3472e63711f2",
                            Translation = "Dédunoka"
                        },
                        new
                        {
                            Id = "37091163-9574-48f0-807f-ca528b5dd90a",
                            Original = "Great-granddaughter",
                            TopicId = "d717aa31-70c0-41b5-8632-3472e63711f2",
                            Translation = "Dédunoka"
                        },
                        new
                        {
                            Id = "142a7886-9628-4326-9517-b7ba74534092",
                            Original = "Team",
                            TopicId = "229f3ebe-81a8-4b8e-a8b6-b82bdbaa723a",
                            Translation = "Csapat"
                        },
                        new
                        {
                            Id = "a0937c30-67e2-4f5e-ad65-7c61d48f1ea0",
                            Original = "Opponent",
                            TopicId = "229f3ebe-81a8-4b8e-a8b6-b82bdbaa723a",
                            Translation = "Ellenfél"
                        },
                        new
                        {
                            Id = "0745c491-bf21-44bb-977a-83cd1ac6d53a",
                            Original = "Stadium",
                            TopicId = "229f3ebe-81a8-4b8e-a8b6-b82bdbaa723a",
                            Translation = "Stadion"
                        },
                        new
                        {
                            Id = "d0264f44-297e-401e-9eba-c37eb5e91c45",
                            Original = "Running",
                            TopicId = "229f3ebe-81a8-4b8e-a8b6-b82bdbaa723a",
                            Translation = "Futás"
                        },
                        new
                        {
                            Id = "c268549f-cc06-4f24-8101-be1daadf016f",
                            Original = "Finish",
                            TopicId = "229f3ebe-81a8-4b8e-a8b6-b82bdbaa723a",
                            Translation = "Cél"
                        },
                        new
                        {
                            Id = "1e93c242-653e-440a-98aa-2feaf8b985b1",
                            Original = "Swimming",
                            TopicId = "229f3ebe-81a8-4b8e-a8b6-b82bdbaa723a",
                            Translation = "Úszás"
                        },
                        new
                        {
                            Id = "87c195f8-760a-41fd-8259-e8999b68a760",
                            Original = "Rope",
                            TopicId = "229f3ebe-81a8-4b8e-a8b6-b82bdbaa723a",
                            Translation = "Kötél"
                        },
                        new
                        {
                            Id = "895447a4-051c-42db-8d80-9a8bf7655f80",
                            Original = "Coach",
                            TopicId = "229f3ebe-81a8-4b8e-a8b6-b82bdbaa723a",
                            Translation = "Edző"
                        },
                        new
                        {
                            Id = "03023803-b3cc-4cc8-b6f0-2f1f49000870",
                            Original = "Final",
                            TopicId = "229f3ebe-81a8-4b8e-a8b6-b82bdbaa723a",
                            Translation = "Döntő"
                        },
                        new
                        {
                            Id = "11c221dd-2a6c-4248-8a2c-af0cc71640a7",
                            Original = "Basketball",
                            TopicId = "229f3ebe-81a8-4b8e-a8b6-b82bdbaa723a",
                            Translation = "Kosárlabda"
                        },
                        new
                        {
                            Id = "bed28035-bb6e-49bf-9e2a-16a1c893735f",
                            Original = "Football",
                            TopicId = "229f3ebe-81a8-4b8e-a8b6-b82bdbaa723a",
                            Translation = "Labdarúgás"
                        },
                        new
                        {
                            Id = "757c7ab7-6fbb-4f13-b48f-d0dd85c444f1",
                            Original = "Tennis",
                            TopicId = "229f3ebe-81a8-4b8e-a8b6-b82bdbaa723a",
                            Translation = "Tenisz"
                        },
                        new
                        {
                            Id = "cb1175d2-93d4-42cf-ba92-ef133629c9dd",
                            Original = "Baseball",
                            TopicId = "229f3ebe-81a8-4b8e-a8b6-b82bdbaa723a",
                            Translation = "Baseball"
                        },
                        new
                        {
                            Id = "85a008fb-b904-423f-9777-1f7ce9d2439b",
                            Original = "Golf",
                            TopicId = "229f3ebe-81a8-4b8e-a8b6-b82bdbaa723a",
                            Translation = "Golf"
                        },
                        new
                        {
                            Id = "1ff02caa-610f-4c61-9131-252a25b0f1a0",
                            Original = "Volleyball",
                            TopicId = "229f3ebe-81a8-4b8e-a8b6-b82bdbaa723a",
                            Translation = "Röplabda"
                        },
                        new
                        {
                            Id = "29d48c52-e602-4db5-997e-fab81f04ba1f",
                            Original = "Hockey",
                            TopicId = "229f3ebe-81a8-4b8e-a8b6-b82bdbaa723a",
                            Translation = "Hoki"
                        },
                        new
                        {
                            Id = "e49a86e4-260b-436d-8034-9a1708715094",
                            Original = "Boxing",
                            TopicId = "229f3ebe-81a8-4b8e-a8b6-b82bdbaa723a",
                            Translation = "Boksz"
                        },
                        new
                        {
                            Id = "ac60c8f0-cb69-4571-8d35-fdfb60e9f1b3",
                            Original = "Athletics",
                            TopicId = "229f3ebe-81a8-4b8e-a8b6-b82bdbaa723a",
                            Translation = "Atlétika"
                        },
                        new
                        {
                            Id = "298ee59d-0359-4a0e-971f-803ab03ab332",
                            Original = "Cycling",
                            TopicId = "229f3ebe-81a8-4b8e-a8b6-b82bdbaa723a",
                            Translation = "Kerékpározás"
                        },
                        new
                        {
                            Id = "be54e9e6-5a53-4371-9ca1-e99276678fba",
                            Original = "Gymnastics",
                            TopicId = "229f3ebe-81a8-4b8e-a8b6-b82bdbaa723a",
                            Translation = "Gimnasztika"
                        },
                        new
                        {
                            Id = "08f76bbe-9341-442f-9c83-5b521193f0e8",
                            Original = "Skiing",
                            TopicId = "229f3ebe-81a8-4b8e-a8b6-b82bdbaa723a",
                            Translation = "Síelés"
                        },
                        new
                        {
                            Id = "2d0000f0-0938-4924-bbe4-8ccc151cd7e3",
                            Original = "Wrestling",
                            TopicId = "229f3ebe-81a8-4b8e-a8b6-b82bdbaa723a",
                            Translation = "Birkózás"
                        },
                        new
                        {
                            Id = "24de935e-3a9f-4275-9c59-246db878b1f0",
                            Original = "Diving",
                            TopicId = "229f3ebe-81a8-4b8e-a8b6-b82bdbaa723a",
                            Translation = "Merülés"
                        },
                        new
                        {
                            Id = "dc06fe8a-7362-4818-93a7-a759db5ed508",
                            Original = "Archery",
                            TopicId = "229f3ebe-81a8-4b8e-a8b6-b82bdbaa723a",
                            Translation = "Íjászat"
                        },
                        new
                        {
                            Id = "c4de93c8-4781-4cf3-8857-5e1505855377",
                            Original = "Surfing",
                            TopicId = "229f3ebe-81a8-4b8e-a8b6-b82bdbaa723a",
                            Translation = "Szörfözés"
                        },
                        new
                        {
                            Id = "35f38af0-10e3-4127-aae8-d924708500b5",
                            Original = "Karate",
                            TopicId = "229f3ebe-81a8-4b8e-a8b6-b82bdbaa723a",
                            Translation = "Karate"
                        },
                        new
                        {
                            Id = "0ffda06d-c6de-4bb0-9e80-ed1eaaa63cdf",
                            Original = "Gym",
                            TopicId = "229f3ebe-81a8-4b8e-a8b6-b82bdbaa723a",
                            Translation = "Edzőterem"
                        },
                        new
                        {
                            Id = "ebc64c31-0328-4a31-b1f9-9f2ff84b676a",
                            Original = "Champion",
                            TopicId = "229f3ebe-81a8-4b8e-a8b6-b82bdbaa723a",
                            Translation = "Bajnok"
                        },
                        new
                        {
                            Id = "f366d539-ecce-40bb-acd0-38ddece1ce95",
                            Original = "Referee",
                            TopicId = "229f3ebe-81a8-4b8e-a8b6-b82bdbaa723a",
                            Translation = "Játékvezető"
                        },
                        new
                        {
                            Id = "bf8f7883-ce9b-4268-ac3d-99f78609987f",
                            Original = "Medal",
                            TopicId = "229f3ebe-81a8-4b8e-a8b6-b82bdbaa723a",
                            Translation = "Érem"
                        },
                        new
                        {
                            Id = "f0909c15-4ace-4a1a-8748-c2fc28fcf677",
                            Original = "Lemon",
                            TopicId = "211b3d26-fb6a-438e-af53-d8124e9c0911",
                            Translation = "Citrom"
                        },
                        new
                        {
                            Id = "1a6752d4-f5fc-422d-b2d1-8ceac2b3cc68",
                            Original = "Peach",
                            TopicId = "211b3d26-fb6a-438e-af53-d8124e9c0911",
                            Translation = "Barack"
                        },
                        new
                        {
                            Id = "31fdbab7-cee6-4554-83bf-a3e12ad52b83",
                            Original = "Bean",
                            TopicId = "211b3d26-fb6a-438e-af53-d8124e9c0911",
                            Translation = "Bab"
                        },
                        new
                        {
                            Id = "2b1d5315-9199-4f23-bdd1-af5269132138",
                            Original = "Pea",
                            TopicId = "211b3d26-fb6a-438e-af53-d8124e9c0911",
                            Translation = "Borsó"
                        },
                        new
                        {
                            Id = "969950d1-f1b6-4997-aabc-edf6f21262fb",
                            Original = "Broccoli",
                            TopicId = "211b3d26-fb6a-438e-af53-d8124e9c0911",
                            Translation = "Brokkoli"
                        },
                        new
                        {
                            Id = "9820d79c-6bd0-4725-b959-9a4fe39c8843",
                            Original = "Corn",
                            TopicId = "211b3d26-fb6a-438e-af53-d8124e9c0911",
                            Translation = "Kukorica"
                        },
                        new
                        {
                            Id = "cecbd99b-d26d-48e0-9da1-ef88ec11a836",
                            Original = "Rice",
                            TopicId = "211b3d26-fb6a-438e-af53-d8124e9c0911",
                            Translation = "Rizs"
                        },
                        new
                        {
                            Id = "67845502-4ead-49b7-a487-3656c49eb7c8",
                            Original = "Mushroom",
                            TopicId = "211b3d26-fb6a-438e-af53-d8124e9c0911",
                            Translation = "Gomba"
                        },
                        new
                        {
                            Id = "2a171a7e-02ec-46e3-a8ae-c32b0610edfd",
                            Original = "Carrot",
                            TopicId = "211b3d26-fb6a-438e-af53-d8124e9c0911",
                            Translation = "Répa"
                        },
                        new
                        {
                            Id = "bdc65f48-e8fc-4ec9-9353-fcb982e74bab",
                            Original = "Apple",
                            TopicId = "211b3d26-fb6a-438e-af53-d8124e9c0911",
                            Translation = "Alma"
                        },
                        new
                        {
                            Id = "3daa6d99-c778-4750-b9a5-3c217cbc301e",
                            Original = "Banana",
                            TopicId = "211b3d26-fb6a-438e-af53-d8124e9c0911",
                            Translation = "Banán"
                        },
                        new
                        {
                            Id = "04bf015d-fabf-45bf-b304-a6ad85653083",
                            Original = "Orange",
                            TopicId = "211b3d26-fb6a-438e-af53-d8124e9c0911",
                            Translation = "Narancs"
                        },
                        new
                        {
                            Id = "44c89a1a-7569-47a0-a639-200c60bee0cb",
                            Original = "Strawberry",
                            TopicId = "211b3d26-fb6a-438e-af53-d8124e9c0911",
                            Translation = "Eper"
                        },
                        new
                        {
                            Id = "f017de93-1bd3-4706-ba9c-7b2327e8ea90",
                            Original = "Grapes",
                            TopicId = "211b3d26-fb6a-438e-af53-d8124e9c0911",
                            Translation = "Szőlő"
                        },
                        new
                        {
                            Id = "c45e084b-87ba-4c98-8eee-cf5b2b9ac9c7",
                            Original = "Watermelon",
                            TopicId = "211b3d26-fb6a-438e-af53-d8124e9c0911",
                            Translation = "Görögdinnye"
                        },
                        new
                        {
                            Id = "61bfd035-a269-4616-b496-f276aa00f864",
                            Original = "Tomato",
                            TopicId = "211b3d26-fb6a-438e-af53-d8124e9c0911",
                            Translation = "Paradicsom"
                        },
                        new
                        {
                            Id = "475af656-d5f6-4884-8c88-385e1d70d8c7",
                            Original = "Potato",
                            TopicId = "211b3d26-fb6a-438e-af53-d8124e9c0911",
                            Translation = "Krumpli"
                        },
                        new
                        {
                            Id = "4106e5d1-672d-4aae-bd1f-e9b9d772b1bb",
                            Original = "Cucumber",
                            TopicId = "211b3d26-fb6a-438e-af53-d8124e9c0911",
                            Translation = "Uborka"
                        },
                        new
                        {
                            Id = "69265688-9884-4690-86e2-9274bbfe86a7",
                            Original = "Cheese",
                            TopicId = "211b3d26-fb6a-438e-af53-d8124e9c0911",
                            Translation = "Sajt"
                        },
                        new
                        {
                            Id = "70bdde49-bb63-466f-bbe1-71bff4373533",
                            Original = "Bread",
                            TopicId = "211b3d26-fb6a-438e-af53-d8124e9c0911",
                            Translation = "Kenyér"
                        },
                        new
                        {
                            Id = "53ae977d-5a53-440d-b7c5-15d26d24c4a5",
                            Original = "Meat",
                            TopicId = "211b3d26-fb6a-438e-af53-d8124e9c0911",
                            Translation = "Hús"
                        },
                        new
                        {
                            Id = "322889a7-2d58-41be-8c08-d54f28cf0fbb",
                            Original = "Fish",
                            TopicId = "211b3d26-fb6a-438e-af53-d8124e9c0911",
                            Translation = "Hal"
                        },
                        new
                        {
                            Id = "f67d678a-6ab4-400d-81da-a58d76d55552",
                            Original = "Egg",
                            TopicId = "211b3d26-fb6a-438e-af53-d8124e9c0911",
                            Translation = "Tojás"
                        },
                        new
                        {
                            Id = "e414ff2a-ba6a-4f31-9f19-5fe9b7c7c393",
                            Original = "Butter",
                            TopicId = "211b3d26-fb6a-438e-af53-d8124e9c0911",
                            Translation = "Vaj"
                        },
                        new
                        {
                            Id = "0d6a6dc4-4284-4cef-ae71-ae9c2cdaf5a9",
                            Original = "Sugar",
                            TopicId = "211b3d26-fb6a-438e-af53-d8124e9c0911",
                            Translation = "Cukor"
                        },
                        new
                        {
                            Id = "4e9d4b93-d5f2-4455-82da-32467a54fa71",
                            Original = "Salt",
                            TopicId = "211b3d26-fb6a-438e-af53-d8124e9c0911",
                            Translation = "Só"
                        },
                        new
                        {
                            Id = "76d057d5-9177-47ea-8853-5c0b4674dc37",
                            Original = "Pepper",
                            TopicId = "211b3d26-fb6a-438e-af53-d8124e9c0911",
                            Translation = "Bors"
                        },
                        new
                        {
                            Id = "79151322-1ee1-4c6a-8722-42cf856013e9",
                            Original = "Honey",
                            TopicId = "211b3d26-fb6a-438e-af53-d8124e9c0911",
                            Translation = "Méz"
                        },
                        new
                        {
                            Id = "323d5a54-f4cc-413f-a664-a34fef2bf0fc",
                            Original = "Ice cream",
                            TopicId = "211b3d26-fb6a-438e-af53-d8124e9c0911",
                            Translation = "Fagylalt"
                        },
                        new
                        {
                            Id = "a1edabbf-3ffb-49d8-ae21-154ad1b59142",
                            Original = "Suitcase",
                            TopicId = "058be191-523d-4501-b6f6-3bf57263d568",
                            Translation = "Bőrönd"
                        },
                        new
                        {
                            Id = "c826d8fb-cca7-435f-96dd-5dd87ee17b4f",
                            Original = "Ferry",
                            TopicId = "058be191-523d-4501-b6f6-3bf57263d568",
                            Translation = "Komp"
                        },
                        new
                        {
                            Id = "bf2092ef-b924-453e-a413-2f7734bd25ff",
                            Original = "Airport",
                            TopicId = "058be191-523d-4501-b6f6-3bf57263d568",
                            Translation = "Reptér"
                        },
                        new
                        {
                            Id = "9f09e020-069a-44ee-9a4f-a0e642cb5f7e",
                            Original = "Travel agency",
                            TopicId = "058be191-523d-4501-b6f6-3bf57263d568",
                            Translation = "Utazási iroda"
                        },
                        new
                        {
                            Id = "a688355d-01f4-48fe-b772-d4d212ed8efb",
                            Original = "Service",
                            TopicId = "058be191-523d-4501-b6f6-3bf57263d568",
                            Translation = "Szolgáltatás"
                        },
                        new
                        {
                            Id = "a9b71551-519e-4979-a127-186f4e7396a9",
                            Original = "Reception",
                            TopicId = "058be191-523d-4501-b6f6-3bf57263d568",
                            Translation = "Recepció"
                        },
                        new
                        {
                            Id = "59a125f1-ee2d-48ae-b5dc-f60d61d673e2",
                            Original = "Delay",
                            TopicId = "058be191-523d-4501-b6f6-3bf57263d568",
                            Translation = "Késés"
                        },
                        new
                        {
                            Id = "2d952cf9-e68b-417e-9d13-11e350775237",
                            Original = "Airline",
                            TopicId = "058be191-523d-4501-b6f6-3bf57263d568",
                            Translation = "Légitársaság"
                        },
                        new
                        {
                            Id = "718cce81-eff8-4f33-aaf2-1bc2c60b8c11",
                            Original = "Passport",
                            TopicId = "058be191-523d-4501-b6f6-3bf57263d568",
                            Translation = "Útlevél"
                        },
                        new
                        {
                            Id = "738d4d8c-178b-44ef-aad6-43ebf2b97477",
                            Original = "Hotel",
                            TopicId = "058be191-523d-4501-b6f6-3bf57263d568",
                            Translation = "Szálloda"
                        },
                        new
                        {
                            Id = "e402b3a5-f7df-46b1-9aa1-696e0a041c9c",
                            Original = "Train",
                            TopicId = "058be191-523d-4501-b6f6-3bf57263d568",
                            Translation = "Vonat"
                        },
                        new
                        {
                            Id = "222b14aa-f63f-4ad2-8200-192b00b60a3a",
                            Original = "Bus",
                            TopicId = "058be191-523d-4501-b6f6-3bf57263d568",
                            Translation = "Busz"
                        },
                        new
                        {
                            Id = "4e57f400-567c-49c5-afde-8f18cd53015d",
                            Original = "Taxi",
                            TopicId = "058be191-523d-4501-b6f6-3bf57263d568",
                            Translation = "Taxi"
                        },
                        new
                        {
                            Id = "c4e3b70c-10e4-46e0-abdf-75feae5cc49e",
                            Original = "Car",
                            TopicId = "058be191-523d-4501-b6f6-3bf57263d568",
                            Translation = "Autó"
                        },
                        new
                        {
                            Id = "7de9d869-7085-4283-99a9-eb05a607475c",
                            Original = "Ticket",
                            TopicId = "058be191-523d-4501-b6f6-3bf57263d568",
                            Translation = "Jegy"
                        },
                        new
                        {
                            Id = "efc6c8c2-cf7b-4915-be2f-fd44e8c2d12d",
                            Original = "Boarding pass",
                            TopicId = "058be191-523d-4501-b6f6-3bf57263d568",
                            Translation = "Beszállókártya"
                        },
                        new
                        {
                            Id = "e5a9e2e7-667b-48ad-a3a2-e0c5be0dbcf4",
                            Original = "Luggage",
                            TopicId = "058be191-523d-4501-b6f6-3bf57263d568",
                            Translation = "Csomag"
                        },
                        new
                        {
                            Id = "69e526d4-0945-41a9-ab29-135c23478a8e",
                            Original = "Destination",
                            TopicId = "058be191-523d-4501-b6f6-3bf57263d568",
                            Translation = "Célállomás"
                        },
                        new
                        {
                            Id = "711c7cb7-4cc6-4ebb-a8b7-f3873e07ab79",
                            Original = "Tourist",
                            TopicId = "058be191-523d-4501-b6f6-3bf57263d568",
                            Translation = "Turista"
                        },
                        new
                        {
                            Id = "3ad1f127-be3a-42a2-9ac6-aaee3e01afc3",
                            Original = "Guide",
                            TopicId = "058be191-523d-4501-b6f6-3bf57263d568",
                            Translation = "Idegenvezető"
                        },
                        new
                        {
                            Id = "89e03846-091e-4c25-8344-84a40e008c9e",
                            Original = "Map",
                            TopicId = "058be191-523d-4501-b6f6-3bf57263d568",
                            Translation = "Térkép"
                        },
                        new
                        {
                            Id = "1f5ed071-bce5-4df7-b746-8df573375fb1",
                            Original = "Beach",
                            TopicId = "058be191-523d-4501-b6f6-3bf57263d568",
                            Translation = "Strand"
                        },
                        new
                        {
                            Id = "f5e8941b-7893-4599-b9b3-c0bdec993334",
                            Original = "Mountain",
                            TopicId = "058be191-523d-4501-b6f6-3bf57263d568",
                            Translation = "Hegy"
                        },
                        new
                        {
                            Id = "01eada5d-57dd-469b-b9a5-355e55bee7d2",
                            Original = "Lake",
                            TopicId = "058be191-523d-4501-b6f6-3bf57263d568",
                            Translation = "Tó"
                        },
                        new
                        {
                            Id = "f1b00c5c-7775-4646-98b5-12d206273bf6",
                            Original = "Island",
                            TopicId = "058be191-523d-4501-b6f6-3bf57263d568",
                            Translation = "Sziget"
                        },
                        new
                        {
                            Id = "47b97f4c-0a74-4985-97e0-4bb8837ad5a3",
                            Original = "Sightseeing",
                            TopicId = "058be191-523d-4501-b6f6-3bf57263d568",
                            Translation = "Városnézés"
                        },
                        new
                        {
                            Id = "06acdf02-693d-43b0-a9e4-d55d99e1cc67",
                            Original = "Currency",
                            TopicId = "058be191-523d-4501-b6f6-3bf57263d568",
                            Translation = "Pénznem"
                        },
                        new
                        {
                            Id = "9d12c34d-a909-4b0c-b93e-dc20a51c39de",
                            Original = "Souvenir",
                            TopicId = "058be191-523d-4501-b6f6-3bf57263d568",
                            Translation = "Szouvenir"
                        },
                        new
                        {
                            Id = "0cc467e2-db0e-41d7-a9aa-f3bce3059b73",
                            Original = "Adventure",
                            TopicId = "058be191-523d-4501-b6f6-3bf57263d568",
                            Translation = "Kaland"
                        },
                        new
                        {
                            Id = "3ed5a587-ad8e-41e9-aa04-b74d525cfcbe",
                            Original = "Dress",
                            TopicId = "8f3b5b7d-b2b5-44e5-bf9d-5cf765efda15",
                            Translation = "Ruha"
                        },
                        new
                        {
                            Id = "8e7f1e8a-17a3-457b-be67-19ac45fc574c",
                            Original = "Fashionable",
                            TopicId = "8f3b5b7d-b2b5-44e5-bf9d-5cf765efda15",
                            Translation = "Divatos"
                        },
                        new
                        {
                            Id = "77723b1a-a884-44e1-b994-5b5a3045647e",
                            Original = "Cap",
                            TopicId = "8f3b5b7d-b2b5-44e5-bf9d-5cf765efda15",
                            Translation = "Sapka"
                        },
                        new
                        {
                            Id = "0e1d923e-b476-4d21-89fe-d6eb4ac0ddf0",
                            Original = "Bathrobe",
                            TopicId = "8f3b5b7d-b2b5-44e5-bf9d-5cf765efda15",
                            Translation = "Fürdőköpeny"
                        },
                        new
                        {
                            Id = "ffcbda1d-d498-467a-8acd-0273fbbdc9b0",
                            Original = "Belt",
                            TopicId = "8f3b5b7d-b2b5-44e5-bf9d-5cf765efda15",
                            Translation = "Öv"
                        },
                        new
                        {
                            Id = "a1dac59d-44c8-4022-8411-27aa3ce687f2",
                            Original = "Jeans",
                            TopicId = "8f3b5b7d-b2b5-44e5-bf9d-5cf765efda15",
                            Translation = "Farmernadrág"
                        },
                        new
                        {
                            Id = "79b36af8-0f47-46e8-b223-1537ee713844",
                            Original = "Boots",
                            TopicId = "8f3b5b7d-b2b5-44e5-bf9d-5cf765efda15",
                            Translation = "Csizma"
                        },
                        new
                        {
                            Id = "3727ab75-4736-4f55-b45f-2bd5d9e57449",
                            Original = "Bracelet",
                            TopicId = "8f3b5b7d-b2b5-44e5-bf9d-5cf765efda15",
                            Translation = "Karkötő"
                        },
                        new
                        {
                            Id = "d78a03f5-a502-45ac-9d12-3e2d343afd85",
                            Original = "Coat",
                            TopicId = "8f3b5b7d-b2b5-44e5-bf9d-5cf765efda15",
                            Translation = "Kabát"
                        },
                        new
                        {
                            Id = "cbb50883-ba66-4811-9659-05d018d0bd53",
                            Original = "Shirt",
                            TopicId = "8f3b5b7d-b2b5-44e5-bf9d-5cf765efda15",
                            Translation = "Ing"
                        },
                        new
                        {
                            Id = "4fe235f1-f9c6-4a9e-9342-ea6259612c87",
                            Original = "T-shirt",
                            TopicId = "8f3b5b7d-b2b5-44e5-bf9d-5cf765efda15",
                            Translation = "Póló"
                        },
                        new
                        {
                            Id = "8524ff17-dfc3-438a-9e9a-1a1f28ab315d",
                            Original = "Skirt",
                            TopicId = "8f3b5b7d-b2b5-44e5-bf9d-5cf765efda15",
                            Translation = "Szoknya"
                        },
                        new
                        {
                            Id = "fe7fdf5b-8304-4610-a6cb-a746b784a2ca",
                            Original = "Trousers",
                            TopicId = "8f3b5b7d-b2b5-44e5-bf9d-5cf765efda15",
                            Translation = "Nadrág"
                        },
                        new
                        {
                            Id = "94ba16dd-f547-49fd-9247-0023a89233f3",
                            Original = "Sweater",
                            TopicId = "8f3b5b7d-b2b5-44e5-bf9d-5cf765efda15",
                            Translation = "Pulóver"
                        },
                        new
                        {
                            Id = "1427d0f5-7119-4748-92c6-e56a7615e50e",
                            Original = "Jacket",
                            TopicId = "8f3b5b7d-b2b5-44e5-bf9d-5cf765efda15",
                            Translation = "Kabát"
                        },
                        new
                        {
                            Id = "4e50e2f0-3666-4abf-980c-8a984a15ff50",
                            Original = "Socks",
                            TopicId = "8f3b5b7d-b2b5-44e5-bf9d-5cf765efda15",
                            Translation = "Zokni"
                        },
                        new
                        {
                            Id = "f169605e-567c-4b7b-8d19-8757b466910c",
                            Original = "Shoes",
                            TopicId = "8f3b5b7d-b2b5-44e5-bf9d-5cf765efda15",
                            Translation = "Cipő"
                        },
                        new
                        {
                            Id = "778642db-3d47-42a3-b249-641a8c0cf337",
                            Original = "Hat",
                            TopicId = "8f3b5b7d-b2b5-44e5-bf9d-5cf765efda15",
                            Translation = "Kalap"
                        },
                        new
                        {
                            Id = "965d53f4-edf7-420c-8f91-34cd494b21d0",
                            Original = "Gloves",
                            TopicId = "8f3b5b7d-b2b5-44e5-bf9d-5cf765efda15",
                            Translation = "Kesztyű"
                        },
                        new
                        {
                            Id = "928c3618-f9d2-413c-b1ef-8005e6839038",
                            Original = "Scarf",
                            TopicId = "8f3b5b7d-b2b5-44e5-bf9d-5cf765efda15",
                            Translation = "Sál"
                        },
                        new
                        {
                            Id = "e02c59da-ab75-4dcb-b3bf-c1554f3a1061",
                            Original = "Underwear",
                            TopicId = "8f3b5b7d-b2b5-44e5-bf9d-5cf765efda15",
                            Translation = "Alsónemű"
                        },
                        new
                        {
                            Id = "50ca6c3f-634a-42cc-b544-f9c92505b6ef",
                            Original = "Pajamas",
                            TopicId = "8f3b5b7d-b2b5-44e5-bf9d-5cf765efda15",
                            Translation = "Pizsama"
                        },
                        new
                        {
                            Id = "5b639996-2d25-49b2-b0c3-59ab14de7179",
                            Original = "Swimsuit",
                            TopicId = "8f3b5b7d-b2b5-44e5-bf9d-5cf765efda15",
                            Translation = "Fürdőruha"
                        },
                        new
                        {
                            Id = "b94b9b0e-5027-48ca-9cbd-f45276f8ac49",
                            Original = "Bikini",
                            TopicId = "8f3b5b7d-b2b5-44e5-bf9d-5cf765efda15",
                            Translation = "Bikini"
                        },
                        new
                        {
                            Id = "fd56a7f3-2292-4044-903f-8f194b8d0522",
                            Original = "Tie",
                            TopicId = "8f3b5b7d-b2b5-44e5-bf9d-5cf765efda15",
                            Translation = "Nyakkendő"
                        },
                        new
                        {
                            Id = "da81ea42-40f3-4c67-a8a9-5f61ed9d9c09",
                            Original = "Handbag",
                            TopicId = "8f3b5b7d-b2b5-44e5-bf9d-5cf765efda15",
                            Translation = "Kézitáska"
                        },
                        new
                        {
                            Id = "62918290-8438-48ce-8527-f689b807f1bb",
                            Original = "Wallet",
                            TopicId = "8f3b5b7d-b2b5-44e5-bf9d-5cf765efda15",
                            Translation = "Pénztárca"
                        },
                        new
                        {
                            Id = "3fc5d467-99ad-428c-908d-be694da87023",
                            Original = "Watch",
                            TopicId = "8f3b5b7d-b2b5-44e5-bf9d-5cf765efda15",
                            Translation = "Óra"
                        },
                        new
                        {
                            Id = "dab4ec53-c882-4277-8c7d-f70c98794c16",
                            Original = "Flowerpot",
                            TopicId = "b7e85018-1d81-4e39-b50f-e213f95579d2",
                            Translation = "Virágcserép"
                        },
                        new
                        {
                            Id = "332f4070-b4fd-4d7b-997b-2a06b269be6b",
                            Original = "Raking",
                            TopicId = "b7e85018-1d81-4e39-b50f-e213f95579d2",
                            Translation = "Gereblyézés"
                        },
                        new
                        {
                            Id = "5f0a0443-4555-4ba8-bdba-89188d8923e2",
                            Original = "Seed",
                            TopicId = "b7e85018-1d81-4e39-b50f-e213f95579d2",
                            Translation = "Mag"
                        },
                        new
                        {
                            Id = "33327233-88d7-4cec-bcb9-92c624b69c2c",
                            Original = "Soil",
                            TopicId = "b7e85018-1d81-4e39-b50f-e213f95579d2",
                            Translation = "Termőföld"
                        },
                        new
                        {
                            Id = "a291e78d-2b14-4d0b-a744-c38d28bcacb5",
                            Original = "Hole",
                            TopicId = "b7e85018-1d81-4e39-b50f-e213f95579d2",
                            Translation = "Lyuk"
                        },
                        new
                        {
                            Id = "63e3534c-15b6-4f76-89f1-4621a2744d92",
                            Original = "Dirt",
                            TopicId = "b7e85018-1d81-4e39-b50f-e213f95579d2",
                            Translation = "Föld"
                        },
                        new
                        {
                            Id = "2d6a69d6-5b44-4f05-9565-efae6569f554",
                            Original = "Lawn mowing",
                            TopicId = "b7e85018-1d81-4e39-b50f-e213f95579d2",
                            Translation = "Fűnyírás"
                        },
                        new
                        {
                            Id = "4d385a97-04c6-4e2d-b0c6-3c14b8e3a8e9",
                            Original = "Spade",
                            TopicId = "b7e85018-1d81-4e39-b50f-e213f95579d2",
                            Translation = "Ásó"
                        },
                        new
                        {
                            Id = "32da101f-1521-460e-bd1f-933cdc04a108",
                            Original = "Wheelbarrow",
                            TopicId = "b7e85018-1d81-4e39-b50f-e213f95579d2",
                            Translation = "Talicska"
                        },
                        new
                        {
                            Id = "bf8ee4e9-6217-46c3-bdcb-4d244b3b1856",
                            Original = "Watering can",
                            TopicId = "b7e85018-1d81-4e39-b50f-e213f95579d2",
                            Translation = "Öntözőkanna"
                        },
                        new
                        {
                            Id = "b1ee970a-ccd5-46c7-ae14-c262c2784601",
                            Original = "Garden hose",
                            TopicId = "b7e85018-1d81-4e39-b50f-e213f95579d2",
                            Translation = "Kerti tömlő"
                        },
                        new
                        {
                            Id = "2b0ca402-3d81-4b79-bb7b-6268c97c2d2d",
                            Original = "Pruning shears",
                            TopicId = "b7e85018-1d81-4e39-b50f-e213f95579d2",
                            Translation = "Metszőolló"
                        },
                        new
                        {
                            Id = "8cc0e8c4-d32c-4220-91cc-323f373c218d",
                            Original = "Garden gloves",
                            TopicId = "b7e85018-1d81-4e39-b50f-e213f95579d2",
                            Translation = "Kerti kesztyű"
                        },
                        new
                        {
                            Id = "c7ce4d9a-716c-4189-aa09-a6475b73f8fb",
                            Original = "Shovel",
                            TopicId = "b7e85018-1d81-4e39-b50f-e213f95579d2",
                            Translation = "Ásó"
                        },
                        new
                        {
                            Id = "1d41e060-5ff7-4590-a89b-0fda05f9eb65",
                            Original = "Rake",
                            TopicId = "b7e85018-1d81-4e39-b50f-e213f95579d2",
                            Translation = "Gereblye"
                        },
                        new
                        {
                            Id = "3eca87c9-0890-4e61-b328-84e18933ba2e",
                            Original = "Garden fork",
                            TopicId = "b7e85018-1d81-4e39-b50f-e213f95579d2",
                            Translation = "Kerti villa"
                        },
                        new
                        {
                            Id = "42874afe-f962-4daf-b927-aaa88d439ef1",
                            Original = "Pruner",
                            TopicId = "b7e85018-1d81-4e39-b50f-e213f95579d2",
                            Translation = "Metszőolló"
                        },
                        new
                        {
                            Id = "c92ade77-bb83-4aed-a5a7-f61f6338f59c",
                            Original = "Garden trowel",
                            TopicId = "b7e85018-1d81-4e39-b50f-e213f95579d2",
                            Translation = "Kerti talicska"
                        },
                        new
                        {
                            Id = "917ffadf-e008-4e8f-b39a-635555380600",
                            Original = "Garden hoe",
                            TopicId = "b7e85018-1d81-4e39-b50f-e213f95579d2",
                            Translation = "Kerti kapa"
                        },
                        new
                        {
                            Id = "2784f4ed-25f7-4d50-ba69-645f4eb032eb",
                            Original = "Garden rake",
                            TopicId = "b7e85018-1d81-4e39-b50f-e213f95579d2",
                            Translation = "Kerti gereblye"
                        },
                        new
                        {
                            Id = "9d03b22e-3642-401b-ac11-b40258469175",
                            Original = "Garden sprayer",
                            TopicId = "b7e85018-1d81-4e39-b50f-e213f95579d2",
                            Translation = "Kerti permetező"
                        },
                        new
                        {
                            Id = "c1f21270-e043-426c-9230-2e9d7e73382e",
                            Original = "Garden cart",
                            TopicId = "b7e85018-1d81-4e39-b50f-e213f95579d2",
                            Translation = "Kerti szekér"
                        },
                        new
                        {
                            Id = "5b2548e7-9acd-46a8-9bdd-b1d2143124ed",
                            Original = "Garden stake",
                            TopicId = "b7e85018-1d81-4e39-b50f-e213f95579d2",
                            Translation = "Kerti tüske"
                        },
                        new
                        {
                            Id = "9ed2759a-6e44-4bc8-bdb0-ef7868c37421",
                            Original = "Garden trellis",
                            TopicId = "b7e85018-1d81-4e39-b50f-e213f95579d2",
                            Translation = "Kerti rács"
                        },
                        new
                        {
                            Id = "ae7b20bb-a295-4536-96e6-e8dfadf470e7",
                            Original = "Plant pot",
                            TopicId = "b7e85018-1d81-4e39-b50f-e213f95579d2",
                            Translation = "Növényi edény"
                        },
                        new
                        {
                            Id = "325a1c43-93ca-4b43-88b9-d7045c87aefc",
                            Original = "Compost bin",
                            TopicId = "b7e85018-1d81-4e39-b50f-e213f95579d2",
                            Translation = "Komposztáló"
                        },
                        new
                        {
                            Id = "6fe27dc2-2cd1-4745-9d63-a03a4e7e0b41",
                            Original = "Garden bench",
                            TopicId = "b7e85018-1d81-4e39-b50f-e213f95579d2",
                            Translation = "Kerti pad"
                        },
                        new
                        {
                            Id = "fc0ed19a-cf3f-468a-af52-320d94c96707",
                            Original = "Garden gnome",
                            TopicId = "b7e85018-1d81-4e39-b50f-e213f95579d2",
                            Translation = "Kerti törpe"
                        });
                });

            modelBuilder.Entity("WordQuiz.Models.WordStatistic", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PlayerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<string>("WordId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("WordId");

                    b.ToTable("WordStatistics");
                });

            modelBuilder.Entity("WordQuiz.Models.Player", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Player");

                    b.HasData(
                        new
                        {
                            Id = "4ce7248c-40dd-4100-9479-ba188dcaf259",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1c61fbd1-4bf0-4639-b1d2-6fa822f451bc",
                            Email = "seedplayer@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedUserName = "SEEDPLAYER@gmail.com",
                            PasswordHash = "AQAAAAEAACcQAAAAENm5xfHW5HtV0YEN47n9N6E9grtGkLZlqco7Q6ozn+bGrdSW5r0Tl4NbEeDPJrwpxw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "13f94942-73af-4964-ad47-a47fd1bc8fdd",
                            TwoFactorEnabled = false,
                            UserName = "seedplayer@gmail.com",
                            PlayerName = "SeedPlayer"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WordQuiz.Models.Word", b =>
                {
                    b.HasOne("WordQuiz.Models.Topic", "Topic")
                        .WithMany("Words")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("WordQuiz.Models.WordStatistic", b =>
                {
                    b.HasOne("WordQuiz.Models.Player", "Player")
                        .WithMany("WordStatistics")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WordQuiz.Models.Word", "Word")
                        .WithMany()
                        .HasForeignKey("WordId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Word");
                });

            modelBuilder.Entity("WordQuiz.Models.Topic", b =>
                {
                    b.Navigation("Words");
                });

            modelBuilder.Entity("WordQuiz.Models.Player", b =>
                {
                    b.Navigation("WordStatistics");
                });
#pragma warning restore 612, 618
        }
    }
}
