// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WordQuiz.Data;

#nullable disable

namespace WordQuiz.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "2",
                            Name = "Player",
                            NormalizedName = "PLAYER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "ef359a77-196a-4e0f-9216-1381ac4601d0",
                            RoleId = "1"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("WordQuiz.Models.Topic", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Topics");

                    b.HasData(
                        new
                        {
                            Id = "647bfa7e-4314-4640-beaa-151275e12291",
                            Description = "Learn how to address your or your partner's family at gatherings.",
                            Title = "Family"
                        },
                        new
                        {
                            Id = "5ca5eddc-16c2-4f8b-bb31-8fbe050ebde7",
                            Description = "These words will help you cheer for your favorite team.",
                            Title = "Sports"
                        },
                        new
                        {
                            Id = "7b68a801-15f0-4ddc-a164-e43c83687f25",
                            Description = "Become an Oxford level green-thumb with this vocabulary.",
                            Title = "Gardening"
                        },
                        new
                        {
                            Id = "83006284-5128-4fad-a877-edad83aa3b9f",
                            Description = "Words related to traveling abroad.",
                            Title = "Travel"
                        },
                        new
                        {
                            Id = "44fe9a36-27bf-468a-b75d-ab2da7a02d27",
                            Description = "Everything you need to know regarding fashion or about simply going shopping for clothes.",
                            Title = "Clothing"
                        },
                        new
                        {
                            Id = "99dd7578-b8e7-4728-9813-9c9bfb9f7f17",
                            Description = "A vocabulary aimed to help you avoid embarrassment while going out to eat.",
                            Title = "Food"
                        });
                });

            modelBuilder.Entity("WordQuiz.Models.Word", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Original")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TopicId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Translation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TopicId");

                    b.ToTable("Words");

                    b.HasData(
                        new
                        {
                            Id = "2a362481-d823-4d4e-9f5a-399cd16adea5",
                            Original = "Father",
                            TopicId = "647bfa7e-4314-4640-beaa-151275e12291",
                            Translation = "Apa"
                        },
                        new
                        {
                            Id = "226a0020-fd97-48ff-9113-2aceb7744505",
                            Original = "Mother",
                            TopicId = "647bfa7e-4314-4640-beaa-151275e12291",
                            Translation = "Anya"
                        },
                        new
                        {
                            Id = "7f2eab09-af3e-49c4-a60b-12a91c697aec",
                            Original = "Aunt",
                            TopicId = "647bfa7e-4314-4640-beaa-151275e12291",
                            Translation = "Nagynéni"
                        },
                        new
                        {
                            Id = "23dfc930-1927-443a-892a-4b4cd4ce8c2d",
                            Original = "Uncle",
                            TopicId = "647bfa7e-4314-4640-beaa-151275e12291",
                            Translation = "Nagybácsi"
                        },
                        new
                        {
                            Id = "2a637aca-e165-4030-a9e2-f62210e1bc9a",
                            Original = "Grandmother",
                            TopicId = "647bfa7e-4314-4640-beaa-151275e12291",
                            Translation = "Nagymama"
                        },
                        new
                        {
                            Id = "ee9d48a2-4f29-4aaf-8b2a-18bb436e1a56",
                            Original = "Grandfather",
                            TopicId = "647bfa7e-4314-4640-beaa-151275e12291",
                            Translation = "Nagypapa"
                        },
                        new
                        {
                            Id = "41e4b538-4b3c-440f-bea3-34db3e43ff62",
                            Original = "Grandfather",
                            TopicId = "647bfa7e-4314-4640-beaa-151275e12291",
                            Translation = "Nagyapa"
                        },
                        new
                        {
                            Id = "97cb1b95-c1b7-4037-8343-79a921b49137",
                            Original = "Mother-in-law",
                            TopicId = "647bfa7e-4314-4640-beaa-151275e12291",
                            Translation = "Anyós"
                        },
                        new
                        {
                            Id = "be3da671-c97c-4589-9a08-67d9aeed0d78",
                            Original = "Father-in-law",
                            TopicId = "647bfa7e-4314-4640-beaa-151275e12291",
                            Translation = "Após"
                        },
                        new
                        {
                            Id = "9912ec53-c116-49ed-98ce-2b04584cc950",
                            Original = "Son",
                            TopicId = "647bfa7e-4314-4640-beaa-151275e12291",
                            Translation = "Fia"
                        },
                        new
                        {
                            Id = "34074980-8633-41a0-aba8-a9360c88b6b6",
                            Original = "Daughter",
                            TopicId = "647bfa7e-4314-4640-beaa-151275e12291",
                            Translation = "Lánya"
                        },
                        new
                        {
                            Id = "80f93de3-84b0-44b9-9636-243c2af50feb",
                            Original = "Brother",
                            TopicId = "647bfa7e-4314-4640-beaa-151275e12291",
                            Translation = "Fivér"
                        },
                        new
                        {
                            Id = "f0c2b552-b0b5-4eb0-9912-461097d0379f",
                            Original = "Sister",
                            TopicId = "647bfa7e-4314-4640-beaa-151275e12291",
                            Translation = "Húg"
                        },
                        new
                        {
                            Id = "24422a0e-95bb-4778-87f6-59725c5271fa",
                            Original = "Cousin",
                            TopicId = "647bfa7e-4314-4640-beaa-151275e12291",
                            Translation = "Unokatestvér"
                        },
                        new
                        {
                            Id = "7633deb7-ebe9-426a-a8f1-2b76aaea3d25",
                            Original = "Nephew",
                            TopicId = "647bfa7e-4314-4640-beaa-151275e12291",
                            Translation = "Unokaöccs"
                        },
                        new
                        {
                            Id = "23d45a5c-0481-48d1-8ee6-26dbc74a6f10",
                            Original = "Niece",
                            TopicId = "647bfa7e-4314-4640-beaa-151275e12291",
                            Translation = "Unokahúg"
                        },
                        new
                        {
                            Id = "d78b6850-b5c5-4f0b-a6b1-9c86bbb44324",
                            Original = "Stepfather",
                            TopicId = "647bfa7e-4314-4640-beaa-151275e12291",
                            Translation = "Mostohaapa"
                        },
                        new
                        {
                            Id = "a1139c0a-b23b-41b6-b27b-8427c37e0a7a",
                            Original = "Stepmother",
                            TopicId = "647bfa7e-4314-4640-beaa-151275e12291",
                            Translation = "Mostohaanya"
                        },
                        new
                        {
                            Id = "817c54df-6598-4c44-97ef-a87531173e38",
                            Original = "Stepson",
                            TopicId = "647bfa7e-4314-4640-beaa-151275e12291",
                            Translation = "Mostohafiú"
                        },
                        new
                        {
                            Id = "91535ae3-c9e2-42fc-af1d-bd11f199e76c",
                            Original = "Stepdaughter",
                            TopicId = "647bfa7e-4314-4640-beaa-151275e12291",
                            Translation = "Mostohalány"
                        },
                        new
                        {
                            Id = "453cbb13-1fdc-4815-bad7-56dda243d3eb",
                            Original = "Half-brother",
                            TopicId = "647bfa7e-4314-4640-beaa-151275e12291",
                            Translation = "Félfivér"
                        },
                        new
                        {
                            Id = "4039bb04-0215-4b17-bcf6-de1ea27c166c",
                            Original = "Half-sister",
                            TopicId = "647bfa7e-4314-4640-beaa-151275e12291",
                            Translation = "Félnővér"
                        },
                        new
                        {
                            Id = "330b6573-f2d9-47d8-bf55-cb23de6ce569",
                            Original = "Sister-in-law",
                            TopicId = "647bfa7e-4314-4640-beaa-151275e12291",
                            Translation = "Sógornő"
                        },
                        new
                        {
                            Id = "3e5ae013-7b33-44f0-a5f7-92d21078f224",
                            Original = "Brother-in-law",
                            TopicId = "647bfa7e-4314-4640-beaa-151275e12291",
                            Translation = "Sógor"
                        },
                        new
                        {
                            Id = "f7a722cb-2c59-4cb7-82e9-82f164d87c06",
                            Original = "Godfather",
                            TopicId = "647bfa7e-4314-4640-beaa-151275e12291",
                            Translation = "Keresztapa"
                        },
                        new
                        {
                            Id = "3f2139e9-a442-49fc-9ccf-1c3acc24e788",
                            Original = "Godmother",
                            TopicId = "647bfa7e-4314-4640-beaa-151275e12291",
                            Translation = "Keresztanya"
                        },
                        new
                        {
                            Id = "172576d8-0f27-4aaf-a7f6-3c4e07d83010",
                            Original = "Great-grandmother",
                            TopicId = "647bfa7e-4314-4640-beaa-151275e12291",
                            Translation = "Dédnagymama"
                        },
                        new
                        {
                            Id = "29905d8b-0360-4e06-bc7b-5e744d5b7c76",
                            Original = "Great-grandfather",
                            TopicId = "647bfa7e-4314-4640-beaa-151275e12291",
                            Translation = "Dédnagypapa"
                        },
                        new
                        {
                            Id = "188235b1-b7da-4ef6-835b-726effe2981d",
                            Original = "Great-grandson",
                            TopicId = "647bfa7e-4314-4640-beaa-151275e12291",
                            Translation = "Dédunoka"
                        },
                        new
                        {
                            Id = "a2b5ec1d-17d4-478f-8979-9aa0709eeef2",
                            Original = "Great-granddaughter",
                            TopicId = "647bfa7e-4314-4640-beaa-151275e12291",
                            Translation = "Dédunoka"
                        },
                        new
                        {
                            Id = "9cb0532f-5d76-4efd-9934-09ddf93ddc04",
                            Original = "Team",
                            TopicId = "5ca5eddc-16c2-4f8b-bb31-8fbe050ebde7",
                            Translation = "Csapat"
                        },
                        new
                        {
                            Id = "1a1b5917-ff6e-4ec5-92ca-1810f3d4675b",
                            Original = "Opponent",
                            TopicId = "5ca5eddc-16c2-4f8b-bb31-8fbe050ebde7",
                            Translation = "Ellenfél"
                        },
                        new
                        {
                            Id = "98cad703-4afd-4ede-b62e-c2c776bf9725",
                            Original = "Stadium",
                            TopicId = "5ca5eddc-16c2-4f8b-bb31-8fbe050ebde7",
                            Translation = "Stadion"
                        },
                        new
                        {
                            Id = "560844b5-56d1-48db-b4c7-512f2472382b",
                            Original = "Running",
                            TopicId = "5ca5eddc-16c2-4f8b-bb31-8fbe050ebde7",
                            Translation = "Futás"
                        },
                        new
                        {
                            Id = "6869e403-62bc-494e-bf8d-68d75dc368a8",
                            Original = "Finish",
                            TopicId = "5ca5eddc-16c2-4f8b-bb31-8fbe050ebde7",
                            Translation = "Cél"
                        },
                        new
                        {
                            Id = "27bcf317-f527-4120-8f39-f2b63b531026",
                            Original = "Swimming",
                            TopicId = "5ca5eddc-16c2-4f8b-bb31-8fbe050ebde7",
                            Translation = "Úszás"
                        },
                        new
                        {
                            Id = "3a3268b3-bb39-429d-bdd0-76053dbce896",
                            Original = "Rope",
                            TopicId = "5ca5eddc-16c2-4f8b-bb31-8fbe050ebde7",
                            Translation = "Kötél"
                        },
                        new
                        {
                            Id = "fefbc6d4-768c-48c2-8319-21eeb5c1d51d",
                            Original = "Coach",
                            TopicId = "5ca5eddc-16c2-4f8b-bb31-8fbe050ebde7",
                            Translation = "Edző"
                        },
                        new
                        {
                            Id = "70495c05-1595-4a45-ae8c-6eb046862ae8",
                            Original = "Final",
                            TopicId = "5ca5eddc-16c2-4f8b-bb31-8fbe050ebde7",
                            Translation = "Döntő"
                        },
                        new
                        {
                            Id = "683c2a93-1686-4915-8750-87cd04dcd402",
                            Original = "Basketball",
                            TopicId = "5ca5eddc-16c2-4f8b-bb31-8fbe050ebde7",
                            Translation = "Kosárlabda"
                        },
                        new
                        {
                            Id = "7f271ff5-e9ca-4feb-adf4-6de58bd0106f",
                            Original = "Football",
                            TopicId = "5ca5eddc-16c2-4f8b-bb31-8fbe050ebde7",
                            Translation = "Labdarúgás"
                        },
                        new
                        {
                            Id = "01078166-6a63-43d3-b12d-ffe0c8a6c9f4",
                            Original = "Tennis",
                            TopicId = "5ca5eddc-16c2-4f8b-bb31-8fbe050ebde7",
                            Translation = "Tenisz"
                        },
                        new
                        {
                            Id = "03679e94-6178-4c8c-a3e3-29e223c1ce2a",
                            Original = "Baseball",
                            TopicId = "5ca5eddc-16c2-4f8b-bb31-8fbe050ebde7",
                            Translation = "Baseball"
                        },
                        new
                        {
                            Id = "c5022f6e-4cf4-46ec-9d1d-0ac08288c2fe",
                            Original = "Golf",
                            TopicId = "5ca5eddc-16c2-4f8b-bb31-8fbe050ebde7",
                            Translation = "Golf"
                        },
                        new
                        {
                            Id = "b329269e-ece6-4130-bb71-d3ad9e6f60d0",
                            Original = "Volleyball",
                            TopicId = "5ca5eddc-16c2-4f8b-bb31-8fbe050ebde7",
                            Translation = "Röplabda"
                        },
                        new
                        {
                            Id = "3b60215a-bea2-4fea-8c7e-287f65e287b8",
                            Original = "Hockey",
                            TopicId = "5ca5eddc-16c2-4f8b-bb31-8fbe050ebde7",
                            Translation = "Hoki"
                        },
                        new
                        {
                            Id = "78cec0dc-1c32-479a-ac0b-bc84c89d1640",
                            Original = "Boxing",
                            TopicId = "5ca5eddc-16c2-4f8b-bb31-8fbe050ebde7",
                            Translation = "Boksz"
                        },
                        new
                        {
                            Id = "b6b9922d-4a48-4ffe-99c3-ae8c570e8187",
                            Original = "Athletics",
                            TopicId = "5ca5eddc-16c2-4f8b-bb31-8fbe050ebde7",
                            Translation = "Atlétika"
                        },
                        new
                        {
                            Id = "ef78173f-b552-432f-8b19-87889d42419e",
                            Original = "Cycling",
                            TopicId = "5ca5eddc-16c2-4f8b-bb31-8fbe050ebde7",
                            Translation = "Kerékpározás"
                        },
                        new
                        {
                            Id = "f92ba7e7-0477-48ce-9fbb-17c366ec546b",
                            Original = "Gymnastics",
                            TopicId = "5ca5eddc-16c2-4f8b-bb31-8fbe050ebde7",
                            Translation = "Gimnasztika"
                        },
                        new
                        {
                            Id = "c0ee81f3-2f90-42a9-9033-21057cf6b530",
                            Original = "Skiing",
                            TopicId = "5ca5eddc-16c2-4f8b-bb31-8fbe050ebde7",
                            Translation = "Síelés"
                        },
                        new
                        {
                            Id = "21fe4307-53ce-4ff2-9b69-511c10975aca",
                            Original = "Wrestling",
                            TopicId = "5ca5eddc-16c2-4f8b-bb31-8fbe050ebde7",
                            Translation = "Birkózás"
                        },
                        new
                        {
                            Id = "0a4bc4a0-4c5f-485a-8584-b5aa5493746a",
                            Original = "Diving",
                            TopicId = "5ca5eddc-16c2-4f8b-bb31-8fbe050ebde7",
                            Translation = "Merülés"
                        },
                        new
                        {
                            Id = "69005d9a-dde8-461e-9ec1-79a48ce4761e",
                            Original = "Archery",
                            TopicId = "5ca5eddc-16c2-4f8b-bb31-8fbe050ebde7",
                            Translation = "Íjászat"
                        },
                        new
                        {
                            Id = "cc41298a-546b-48d9-9359-92d9655a5491",
                            Original = "Surfing",
                            TopicId = "5ca5eddc-16c2-4f8b-bb31-8fbe050ebde7",
                            Translation = "Szörfözés"
                        },
                        new
                        {
                            Id = "eb1fbfad-e268-4fa2-949c-0c2b1dcd945b",
                            Original = "Karate",
                            TopicId = "5ca5eddc-16c2-4f8b-bb31-8fbe050ebde7",
                            Translation = "Karate"
                        },
                        new
                        {
                            Id = "3efa9f68-e693-4ab4-b9ae-db9900726aba",
                            Original = "Gym",
                            TopicId = "5ca5eddc-16c2-4f8b-bb31-8fbe050ebde7",
                            Translation = "Edzőterem"
                        },
                        new
                        {
                            Id = "accf6bce-9595-4fab-aa4a-08810549c82c",
                            Original = "Champion",
                            TopicId = "5ca5eddc-16c2-4f8b-bb31-8fbe050ebde7",
                            Translation = "Bajnok"
                        },
                        new
                        {
                            Id = "364640aa-1ac3-4a93-9f1c-91fa05772351",
                            Original = "Referee",
                            TopicId = "5ca5eddc-16c2-4f8b-bb31-8fbe050ebde7",
                            Translation = "Játékvezető"
                        },
                        new
                        {
                            Id = "5fa5123e-94d9-4551-be42-71ce2f087aff",
                            Original = "Medal",
                            TopicId = "5ca5eddc-16c2-4f8b-bb31-8fbe050ebde7",
                            Translation = "Érem"
                        },
                        new
                        {
                            Id = "6ac4ccbb-7233-44d2-bba6-6c54d8b9def1",
                            Original = "Lemon",
                            TopicId = "99dd7578-b8e7-4728-9813-9c9bfb9f7f17",
                            Translation = "Citrom"
                        },
                        new
                        {
                            Id = "8e356a0c-dcb8-4a35-b576-5e3678b0174f",
                            Original = "Peach",
                            TopicId = "99dd7578-b8e7-4728-9813-9c9bfb9f7f17",
                            Translation = "Barack"
                        },
                        new
                        {
                            Id = "7d31cf20-1662-4296-944e-47eb3aae314a",
                            Original = "Bean",
                            TopicId = "99dd7578-b8e7-4728-9813-9c9bfb9f7f17",
                            Translation = "Bab"
                        },
                        new
                        {
                            Id = "c42923e9-3a62-4691-92a4-523450565dac",
                            Original = "Pea",
                            TopicId = "99dd7578-b8e7-4728-9813-9c9bfb9f7f17",
                            Translation = "Borsó"
                        },
                        new
                        {
                            Id = "315ddebe-4af5-46be-af91-120d4d525573",
                            Original = "Broccoli",
                            TopicId = "99dd7578-b8e7-4728-9813-9c9bfb9f7f17",
                            Translation = "Brokkoli"
                        },
                        new
                        {
                            Id = "33e06efa-2122-4589-8016-5a024b17bc90",
                            Original = "Corn",
                            TopicId = "99dd7578-b8e7-4728-9813-9c9bfb9f7f17",
                            Translation = "Kukorica"
                        },
                        new
                        {
                            Id = "cc9bfa52-3723-4518-a587-cc7cb71df434",
                            Original = "Rice",
                            TopicId = "99dd7578-b8e7-4728-9813-9c9bfb9f7f17",
                            Translation = "Rizs"
                        },
                        new
                        {
                            Id = "694a805e-a804-4d3c-9aaa-2cd99cf7d9db",
                            Original = "Mushroom",
                            TopicId = "99dd7578-b8e7-4728-9813-9c9bfb9f7f17",
                            Translation = "Gomba"
                        },
                        new
                        {
                            Id = "bcfadcbb-3beb-46fd-86a8-4c7a87752da9",
                            Original = "Carrot",
                            TopicId = "99dd7578-b8e7-4728-9813-9c9bfb9f7f17",
                            Translation = "Répa"
                        },
                        new
                        {
                            Id = "59f88726-783e-4b67-8db4-27ba6aeb31df",
                            Original = "Apple",
                            TopicId = "99dd7578-b8e7-4728-9813-9c9bfb9f7f17",
                            Translation = "Alma"
                        },
                        new
                        {
                            Id = "ce8e0f53-0bcb-454b-8299-570f3bd4348d",
                            Original = "Banana",
                            TopicId = "99dd7578-b8e7-4728-9813-9c9bfb9f7f17",
                            Translation = "Banán"
                        },
                        new
                        {
                            Id = "fdb99c0d-8090-4df3-91ff-9959dfc7d3ce",
                            Original = "Orange",
                            TopicId = "99dd7578-b8e7-4728-9813-9c9bfb9f7f17",
                            Translation = "Narancs"
                        },
                        new
                        {
                            Id = "69e5c983-ea59-43d6-b8cd-47be45b48b6f",
                            Original = "Strawberry",
                            TopicId = "99dd7578-b8e7-4728-9813-9c9bfb9f7f17",
                            Translation = "Eper"
                        },
                        new
                        {
                            Id = "56e04ace-d36e-407d-b9dd-f0cc80eab323",
                            Original = "Grapes",
                            TopicId = "99dd7578-b8e7-4728-9813-9c9bfb9f7f17",
                            Translation = "Szőlő"
                        },
                        new
                        {
                            Id = "20edd234-5699-4d61-b320-a2954b1475c7",
                            Original = "Watermelon",
                            TopicId = "99dd7578-b8e7-4728-9813-9c9bfb9f7f17",
                            Translation = "Görögdinnye"
                        },
                        new
                        {
                            Id = "ff49c96e-8b34-4a90-81c4-21b9dbcccea5",
                            Original = "Tomato",
                            TopicId = "99dd7578-b8e7-4728-9813-9c9bfb9f7f17",
                            Translation = "Paradicsom"
                        },
                        new
                        {
                            Id = "adc4e43b-d20d-4315-9c54-9a2e8093c00c",
                            Original = "Potato",
                            TopicId = "99dd7578-b8e7-4728-9813-9c9bfb9f7f17",
                            Translation = "Krumpli"
                        },
                        new
                        {
                            Id = "bf073520-bcae-474d-8b20-81061c39c494",
                            Original = "Cucumber",
                            TopicId = "99dd7578-b8e7-4728-9813-9c9bfb9f7f17",
                            Translation = "Uborka"
                        },
                        new
                        {
                            Id = "356cecc7-a3e7-460b-9e0f-3ed6b7783890",
                            Original = "Cheese",
                            TopicId = "99dd7578-b8e7-4728-9813-9c9bfb9f7f17",
                            Translation = "Sajt"
                        },
                        new
                        {
                            Id = "16635eef-838e-4f5c-9102-acce6a575726",
                            Original = "Bread",
                            TopicId = "99dd7578-b8e7-4728-9813-9c9bfb9f7f17",
                            Translation = "Kenyér"
                        },
                        new
                        {
                            Id = "8b3b2731-3919-44ea-81f6-de6ec42e3c0c",
                            Original = "Meat",
                            TopicId = "99dd7578-b8e7-4728-9813-9c9bfb9f7f17",
                            Translation = "Hús"
                        },
                        new
                        {
                            Id = "e311a4a6-5432-44b5-a9da-ee0b1bdf764c",
                            Original = "Fish",
                            TopicId = "99dd7578-b8e7-4728-9813-9c9bfb9f7f17",
                            Translation = "Hal"
                        },
                        new
                        {
                            Id = "cf69a620-3e14-4755-b4cf-fc83a02f89b1",
                            Original = "Egg",
                            TopicId = "99dd7578-b8e7-4728-9813-9c9bfb9f7f17",
                            Translation = "Tojás"
                        },
                        new
                        {
                            Id = "d3a9c894-1e53-4731-816f-63d1d7ffff01",
                            Original = "Butter",
                            TopicId = "99dd7578-b8e7-4728-9813-9c9bfb9f7f17",
                            Translation = "Vaj"
                        },
                        new
                        {
                            Id = "4a0cc628-ad3d-45d6-b9f7-e23ffe587803",
                            Original = "Sugar",
                            TopicId = "99dd7578-b8e7-4728-9813-9c9bfb9f7f17",
                            Translation = "Cukor"
                        },
                        new
                        {
                            Id = "fca40a44-91f5-46b2-be13-c08222db7b94",
                            Original = "Salt",
                            TopicId = "99dd7578-b8e7-4728-9813-9c9bfb9f7f17",
                            Translation = "Só"
                        },
                        new
                        {
                            Id = "9dc6cb23-2817-459f-918d-a8d58fbe2409",
                            Original = "Pepper",
                            TopicId = "99dd7578-b8e7-4728-9813-9c9bfb9f7f17",
                            Translation = "Bors"
                        },
                        new
                        {
                            Id = "3621d517-36be-4c59-a263-3bebb4ee2ac5",
                            Original = "Honey",
                            TopicId = "99dd7578-b8e7-4728-9813-9c9bfb9f7f17",
                            Translation = "Méz"
                        },
                        new
                        {
                            Id = "de543f59-38b4-4eb3-a88c-6b698da40cbc",
                            Original = "Ice cream",
                            TopicId = "99dd7578-b8e7-4728-9813-9c9bfb9f7f17",
                            Translation = "Fagylalt"
                        },
                        new
                        {
                            Id = "b3f832af-a989-4483-9d7f-d3a197af57e6",
                            Original = "Suitcase",
                            TopicId = "83006284-5128-4fad-a877-edad83aa3b9f",
                            Translation = "Bőrönd"
                        },
                        new
                        {
                            Id = "9cdbd50c-07b9-4dd3-8b2a-9e095b0592ff",
                            Original = "Ferry",
                            TopicId = "83006284-5128-4fad-a877-edad83aa3b9f",
                            Translation = "Komp"
                        },
                        new
                        {
                            Id = "8e796924-74de-4fb3-a5e7-19deb57fd790",
                            Original = "Airport",
                            TopicId = "83006284-5128-4fad-a877-edad83aa3b9f",
                            Translation = "Reptér"
                        },
                        new
                        {
                            Id = "0893a104-1d79-4e15-9dbd-5c07a7476474",
                            Original = "Travel agency",
                            TopicId = "83006284-5128-4fad-a877-edad83aa3b9f",
                            Translation = "Utazási iroda"
                        },
                        new
                        {
                            Id = "35ec9d7f-dd73-447b-81d0-6850b671e144",
                            Original = "Service",
                            TopicId = "83006284-5128-4fad-a877-edad83aa3b9f",
                            Translation = "Szolgáltatás"
                        },
                        new
                        {
                            Id = "1a3dc8be-424b-40b4-a799-1ab9748ce6a8",
                            Original = "Reception",
                            TopicId = "83006284-5128-4fad-a877-edad83aa3b9f",
                            Translation = "Recepció"
                        },
                        new
                        {
                            Id = "75274785-ba14-48eb-993b-dd2668ed99c1",
                            Original = "Delay",
                            TopicId = "83006284-5128-4fad-a877-edad83aa3b9f",
                            Translation = "Késés"
                        },
                        new
                        {
                            Id = "68f21638-6aa4-4b41-871b-4b3abe0ac68b",
                            Original = "Airline",
                            TopicId = "83006284-5128-4fad-a877-edad83aa3b9f",
                            Translation = "Légitársaság"
                        },
                        new
                        {
                            Id = "5645ef18-d7a7-4422-858b-9d4409baab95",
                            Original = "Passport",
                            TopicId = "83006284-5128-4fad-a877-edad83aa3b9f",
                            Translation = "Útlevél"
                        },
                        new
                        {
                            Id = "2089c011-b1b7-4f0a-87fa-fd821e331f01",
                            Original = "Hotel",
                            TopicId = "83006284-5128-4fad-a877-edad83aa3b9f",
                            Translation = "Szálloda"
                        },
                        new
                        {
                            Id = "50e3745f-c7d7-45cd-90b7-fe24fd7fc60d",
                            Original = "Train",
                            TopicId = "83006284-5128-4fad-a877-edad83aa3b9f",
                            Translation = "Vonat"
                        },
                        new
                        {
                            Id = "3a0c1098-b21a-4b4c-8948-ec33cd1b3242",
                            Original = "Bus",
                            TopicId = "83006284-5128-4fad-a877-edad83aa3b9f",
                            Translation = "Busz"
                        },
                        new
                        {
                            Id = "b880f3b1-b6ba-4391-9f0b-0b99550f4c5a",
                            Original = "Taxi",
                            TopicId = "83006284-5128-4fad-a877-edad83aa3b9f",
                            Translation = "Taxi"
                        },
                        new
                        {
                            Id = "cffddfa3-b6a4-426d-967f-9f4a30d9b4aa",
                            Original = "Car",
                            TopicId = "83006284-5128-4fad-a877-edad83aa3b9f",
                            Translation = "Autó"
                        },
                        new
                        {
                            Id = "61e5fdea-d0b7-4ad5-a7f3-d348266eb179",
                            Original = "Ticket",
                            TopicId = "83006284-5128-4fad-a877-edad83aa3b9f",
                            Translation = "Jegy"
                        },
                        new
                        {
                            Id = "07275fa2-0a27-4823-91a4-55be7e994826",
                            Original = "Boarding pass",
                            TopicId = "83006284-5128-4fad-a877-edad83aa3b9f",
                            Translation = "Beszállókártya"
                        },
                        new
                        {
                            Id = "72d1b11c-8131-4f0e-bd4f-0fc6b1b9980a",
                            Original = "Luggage",
                            TopicId = "83006284-5128-4fad-a877-edad83aa3b9f",
                            Translation = "Csomag"
                        },
                        new
                        {
                            Id = "242734aa-74db-40cd-b38d-34f8cf666247",
                            Original = "Destination",
                            TopicId = "83006284-5128-4fad-a877-edad83aa3b9f",
                            Translation = "Célállomás"
                        },
                        new
                        {
                            Id = "36d3c807-6907-47f2-9f08-0894db59450b",
                            Original = "Tourist",
                            TopicId = "83006284-5128-4fad-a877-edad83aa3b9f",
                            Translation = "Turista"
                        },
                        new
                        {
                            Id = "077b1509-d324-4c1c-a040-19aea351bda4",
                            Original = "Guide",
                            TopicId = "83006284-5128-4fad-a877-edad83aa3b9f",
                            Translation = "Idegenvezető"
                        },
                        new
                        {
                            Id = "4e03a077-08e0-4395-8609-75c86d11043d",
                            Original = "Map",
                            TopicId = "83006284-5128-4fad-a877-edad83aa3b9f",
                            Translation = "Térkép"
                        },
                        new
                        {
                            Id = "3f1ce9c9-c318-44e6-b192-5abaa786b7b3",
                            Original = "Beach",
                            TopicId = "83006284-5128-4fad-a877-edad83aa3b9f",
                            Translation = "Strand"
                        },
                        new
                        {
                            Id = "16681583-c002-499e-8218-e11bead5e332",
                            Original = "Mountain",
                            TopicId = "83006284-5128-4fad-a877-edad83aa3b9f",
                            Translation = "Hegy"
                        },
                        new
                        {
                            Id = "fb1cb957-7561-472e-9322-d952a9dcf1ba",
                            Original = "Lake",
                            TopicId = "83006284-5128-4fad-a877-edad83aa3b9f",
                            Translation = "Tó"
                        },
                        new
                        {
                            Id = "2db3c158-ee32-4d8b-a0a0-82cb7934daa2",
                            Original = "Island",
                            TopicId = "83006284-5128-4fad-a877-edad83aa3b9f",
                            Translation = "Sziget"
                        },
                        new
                        {
                            Id = "2fc8ac7c-f711-4d3b-98d7-1e4e440e87b4",
                            Original = "Sightseeing",
                            TopicId = "83006284-5128-4fad-a877-edad83aa3b9f",
                            Translation = "Városnézés"
                        },
                        new
                        {
                            Id = "79d8ce6b-92ca-470c-ac41-d1796142218c",
                            Original = "Currency",
                            TopicId = "83006284-5128-4fad-a877-edad83aa3b9f",
                            Translation = "Pénznem"
                        },
                        new
                        {
                            Id = "b0aa219f-0f5d-4730-8c36-52575b054f71",
                            Original = "Souvenir",
                            TopicId = "83006284-5128-4fad-a877-edad83aa3b9f",
                            Translation = "Szouvenir"
                        },
                        new
                        {
                            Id = "2ed0ae48-5452-42ab-9fd4-ef68ad6a451c",
                            Original = "Adventure",
                            TopicId = "83006284-5128-4fad-a877-edad83aa3b9f",
                            Translation = "Kaland"
                        },
                        new
                        {
                            Id = "f2b53256-3444-4613-925c-7af7e053ca32",
                            Original = "Dress",
                            TopicId = "44fe9a36-27bf-468a-b75d-ab2da7a02d27",
                            Translation = "Ruha"
                        },
                        new
                        {
                            Id = "2a987d08-266a-49e2-a68d-f4141a16edd4",
                            Original = "Fashionable",
                            TopicId = "44fe9a36-27bf-468a-b75d-ab2da7a02d27",
                            Translation = "Divatos"
                        },
                        new
                        {
                            Id = "a5bfe016-790d-439f-821b-faf939c74525",
                            Original = "Cap",
                            TopicId = "44fe9a36-27bf-468a-b75d-ab2da7a02d27",
                            Translation = "Sapka"
                        },
                        new
                        {
                            Id = "dc50a877-922a-4552-bff4-8ff39219c768",
                            Original = "Bathrobe",
                            TopicId = "44fe9a36-27bf-468a-b75d-ab2da7a02d27",
                            Translation = "Fürdőköpeny"
                        },
                        new
                        {
                            Id = "15b575a0-98a8-45d1-8c66-d655e39a9f00",
                            Original = "Belt",
                            TopicId = "44fe9a36-27bf-468a-b75d-ab2da7a02d27",
                            Translation = "Öv"
                        },
                        new
                        {
                            Id = "ce55a2c4-fb24-4a6e-a3c6-3a7c28098d87",
                            Original = "Jeans",
                            TopicId = "44fe9a36-27bf-468a-b75d-ab2da7a02d27",
                            Translation = "Farmernadrág"
                        },
                        new
                        {
                            Id = "6555fae1-d674-49f0-9795-b09a5c8c020a",
                            Original = "Boots",
                            TopicId = "44fe9a36-27bf-468a-b75d-ab2da7a02d27",
                            Translation = "Csizma"
                        },
                        new
                        {
                            Id = "1d4cfef8-5679-43cb-888f-b27225a7b0ae",
                            Original = "Bracelet",
                            TopicId = "44fe9a36-27bf-468a-b75d-ab2da7a02d27",
                            Translation = "Karkötő"
                        },
                        new
                        {
                            Id = "38f8d04a-f0e2-49db-9a7a-6ea670a426bc",
                            Original = "Coat",
                            TopicId = "44fe9a36-27bf-468a-b75d-ab2da7a02d27",
                            Translation = "Kabát"
                        },
                        new
                        {
                            Id = "b157a11c-8b71-4a22-861c-8497d8aae1c4",
                            Original = "Shirt",
                            TopicId = "44fe9a36-27bf-468a-b75d-ab2da7a02d27",
                            Translation = "Ing"
                        },
                        new
                        {
                            Id = "109c56e1-c344-4df8-bb8a-15482db22019",
                            Original = "T-shirt",
                            TopicId = "44fe9a36-27bf-468a-b75d-ab2da7a02d27",
                            Translation = "Póló"
                        },
                        new
                        {
                            Id = "81869dae-488e-472f-8437-85d6c7e80abe",
                            Original = "Skirt",
                            TopicId = "44fe9a36-27bf-468a-b75d-ab2da7a02d27",
                            Translation = "Szoknya"
                        },
                        new
                        {
                            Id = "427511ca-22eb-4b84-812d-d28c94775330",
                            Original = "Trousers",
                            TopicId = "44fe9a36-27bf-468a-b75d-ab2da7a02d27",
                            Translation = "Nadrág"
                        },
                        new
                        {
                            Id = "d13dac83-89a4-4a6e-9de5-f8dd376fdcf2",
                            Original = "Sweater",
                            TopicId = "44fe9a36-27bf-468a-b75d-ab2da7a02d27",
                            Translation = "Pulóver"
                        },
                        new
                        {
                            Id = "a2d8b566-b864-42f3-89b7-2195e9da2d71",
                            Original = "Jacket",
                            TopicId = "44fe9a36-27bf-468a-b75d-ab2da7a02d27",
                            Translation = "Kabát"
                        },
                        new
                        {
                            Id = "ed01835f-d67b-4fe9-9064-423e05b24c13",
                            Original = "Socks",
                            TopicId = "44fe9a36-27bf-468a-b75d-ab2da7a02d27",
                            Translation = "Zokni"
                        },
                        new
                        {
                            Id = "dbe73d21-9188-439e-b676-8cd03f10bd1e",
                            Original = "Shoes",
                            TopicId = "44fe9a36-27bf-468a-b75d-ab2da7a02d27",
                            Translation = "Cipő"
                        },
                        new
                        {
                            Id = "26e28558-bcb8-439a-8721-ee87eda521d5",
                            Original = "Hat",
                            TopicId = "44fe9a36-27bf-468a-b75d-ab2da7a02d27",
                            Translation = "Kalap"
                        },
                        new
                        {
                            Id = "06578855-d864-4db0-bb2f-cd5579555d87",
                            Original = "Gloves",
                            TopicId = "44fe9a36-27bf-468a-b75d-ab2da7a02d27",
                            Translation = "Kesztyű"
                        },
                        new
                        {
                            Id = "3a762716-941c-4856-a829-2349a6dec7c0",
                            Original = "Scarf",
                            TopicId = "44fe9a36-27bf-468a-b75d-ab2da7a02d27",
                            Translation = "Sál"
                        },
                        new
                        {
                            Id = "01ab9fad-f30d-4cfa-b3e3-d41af0f4d60a",
                            Original = "Underwear",
                            TopicId = "44fe9a36-27bf-468a-b75d-ab2da7a02d27",
                            Translation = "Alsónemű"
                        },
                        new
                        {
                            Id = "403851db-4f82-46cb-8a75-ab03db54fc61",
                            Original = "Pajamas",
                            TopicId = "44fe9a36-27bf-468a-b75d-ab2da7a02d27",
                            Translation = "Pizsama"
                        },
                        new
                        {
                            Id = "dd2b33e2-5974-4fe2-892c-07197074d31c",
                            Original = "Swimsuit",
                            TopicId = "44fe9a36-27bf-468a-b75d-ab2da7a02d27",
                            Translation = "Fürdőruha"
                        },
                        new
                        {
                            Id = "edc85930-9315-41f1-9360-1abc25d3b25a",
                            Original = "Bikini",
                            TopicId = "44fe9a36-27bf-468a-b75d-ab2da7a02d27",
                            Translation = "Bikini"
                        },
                        new
                        {
                            Id = "15dc981a-86ca-4048-b83b-35cfae454970",
                            Original = "Tie",
                            TopicId = "44fe9a36-27bf-468a-b75d-ab2da7a02d27",
                            Translation = "Nyakkendő"
                        },
                        new
                        {
                            Id = "82997420-3865-4b02-9f24-d0b0245673c4",
                            Original = "Handbag",
                            TopicId = "44fe9a36-27bf-468a-b75d-ab2da7a02d27",
                            Translation = "Kézitáska"
                        },
                        new
                        {
                            Id = "ce4fda20-5a1f-4a4e-9b67-f195504b91f6",
                            Original = "Wallet",
                            TopicId = "44fe9a36-27bf-468a-b75d-ab2da7a02d27",
                            Translation = "Pénztárca"
                        },
                        new
                        {
                            Id = "dd57bc12-4db4-4d43-ac9b-b29b4084b473",
                            Original = "Watch",
                            TopicId = "44fe9a36-27bf-468a-b75d-ab2da7a02d27",
                            Translation = "Óra"
                        },
                        new
                        {
                            Id = "a0d28bc6-6ca7-4ccc-b5fd-df5634501c79",
                            Original = "Flowerpot",
                            TopicId = "7b68a801-15f0-4ddc-a164-e43c83687f25",
                            Translation = "Virágcserép"
                        },
                        new
                        {
                            Id = "b0550cab-7857-4f84-a097-7c23179b46bb",
                            Original = "Raking",
                            TopicId = "7b68a801-15f0-4ddc-a164-e43c83687f25",
                            Translation = "Gereblyézés"
                        },
                        new
                        {
                            Id = "3dc045a7-6868-4e1d-9be7-d2cfc31e4496",
                            Original = "Seed",
                            TopicId = "7b68a801-15f0-4ddc-a164-e43c83687f25",
                            Translation = "Mag"
                        },
                        new
                        {
                            Id = "075f1649-8180-4a84-b8f4-be6f8bcb7b45",
                            Original = "Soil",
                            TopicId = "7b68a801-15f0-4ddc-a164-e43c83687f25",
                            Translation = "Termőföld"
                        },
                        new
                        {
                            Id = "16fcef79-edee-4d98-9736-3711ce726912",
                            Original = "Hole",
                            TopicId = "7b68a801-15f0-4ddc-a164-e43c83687f25",
                            Translation = "Lyuk"
                        },
                        new
                        {
                            Id = "5cfd0bfa-47bc-425d-a553-1e3e9dcc10e0",
                            Original = "Dirt",
                            TopicId = "7b68a801-15f0-4ddc-a164-e43c83687f25",
                            Translation = "Föld"
                        },
                        new
                        {
                            Id = "0e2b1e2b-902d-41eb-bd05-5e095a5fecf3",
                            Original = "Lawn mowing",
                            TopicId = "7b68a801-15f0-4ddc-a164-e43c83687f25",
                            Translation = "Fűnyírás"
                        },
                        new
                        {
                            Id = "880aed5e-9c7c-4332-adeb-b0566c0a6260",
                            Original = "Spade",
                            TopicId = "7b68a801-15f0-4ddc-a164-e43c83687f25",
                            Translation = "Ásó"
                        },
                        new
                        {
                            Id = "0a2bf8f9-c757-4137-8b75-9985ce070f71",
                            Original = "Wheelbarrow",
                            TopicId = "7b68a801-15f0-4ddc-a164-e43c83687f25",
                            Translation = "Talicska"
                        },
                        new
                        {
                            Id = "d1bfa1cd-2536-402f-b53c-208c3419b7d9",
                            Original = "Watering can",
                            TopicId = "7b68a801-15f0-4ddc-a164-e43c83687f25",
                            Translation = "Öntözőkanna"
                        },
                        new
                        {
                            Id = "57a863bb-1766-4173-8f7d-68456a31c229",
                            Original = "Garden hose",
                            TopicId = "7b68a801-15f0-4ddc-a164-e43c83687f25",
                            Translation = "Kerti tömlő"
                        },
                        new
                        {
                            Id = "f07a3b83-95ce-487b-9ca4-bc8e61f31074",
                            Original = "Pruning shears",
                            TopicId = "7b68a801-15f0-4ddc-a164-e43c83687f25",
                            Translation = "Metszőolló"
                        },
                        new
                        {
                            Id = "7f6efbb7-d8c6-4d4e-9acc-e592f6a7531b",
                            Original = "Garden gloves",
                            TopicId = "7b68a801-15f0-4ddc-a164-e43c83687f25",
                            Translation = "Kerti kesztyű"
                        },
                        new
                        {
                            Id = "86a01e8b-b962-41e5-9aa2-96ac0f7a9c93",
                            Original = "Shovel",
                            TopicId = "7b68a801-15f0-4ddc-a164-e43c83687f25",
                            Translation = "Ásó"
                        },
                        new
                        {
                            Id = "b0c38406-b5a2-41ae-b39e-751c4eb87fa7",
                            Original = "Rake",
                            TopicId = "7b68a801-15f0-4ddc-a164-e43c83687f25",
                            Translation = "Gereblye"
                        },
                        new
                        {
                            Id = "79785406-bbda-4026-a269-048ccd4c7f8d",
                            Original = "Garden fork",
                            TopicId = "7b68a801-15f0-4ddc-a164-e43c83687f25",
                            Translation = "Kerti villa"
                        },
                        new
                        {
                            Id = "cf003e92-b372-4cdc-9a76-dad5888764b5",
                            Original = "Pruner",
                            TopicId = "7b68a801-15f0-4ddc-a164-e43c83687f25",
                            Translation = "Metszőolló"
                        },
                        new
                        {
                            Id = "b100269e-290e-42c8-9ef7-362e2772e2a3",
                            Original = "Garden trowel",
                            TopicId = "7b68a801-15f0-4ddc-a164-e43c83687f25",
                            Translation = "Kerti talicska"
                        },
                        new
                        {
                            Id = "7acfb5ec-97e7-4806-9af2-00389184a315",
                            Original = "Garden hoe",
                            TopicId = "7b68a801-15f0-4ddc-a164-e43c83687f25",
                            Translation = "Kerti kapa"
                        },
                        new
                        {
                            Id = "4178d2fd-c0d6-4e01-be34-5b7c7c2325c4",
                            Original = "Garden rake",
                            TopicId = "7b68a801-15f0-4ddc-a164-e43c83687f25",
                            Translation = "Kerti gereblye"
                        },
                        new
                        {
                            Id = "357d142c-45b6-4b6f-a6c7-a1571ddf233c",
                            Original = "Garden sprayer",
                            TopicId = "7b68a801-15f0-4ddc-a164-e43c83687f25",
                            Translation = "Kerti permetező"
                        },
                        new
                        {
                            Id = "832ff1e5-352f-463a-82b6-349849d3f07d",
                            Original = "Garden cart",
                            TopicId = "7b68a801-15f0-4ddc-a164-e43c83687f25",
                            Translation = "Kerti szekér"
                        },
                        new
                        {
                            Id = "f34a9829-8672-40b4-9671-78bfb1b3110c",
                            Original = "Garden stake",
                            TopicId = "7b68a801-15f0-4ddc-a164-e43c83687f25",
                            Translation = "Kerti tüske"
                        },
                        new
                        {
                            Id = "70f818a4-ab19-4d02-bcb6-ac06b8435b69",
                            Original = "Garden trellis",
                            TopicId = "7b68a801-15f0-4ddc-a164-e43c83687f25",
                            Translation = "Kerti rács"
                        },
                        new
                        {
                            Id = "81df600c-dac2-451a-a044-c887ea3ac9c3",
                            Original = "Plant pot",
                            TopicId = "7b68a801-15f0-4ddc-a164-e43c83687f25",
                            Translation = "Növényi edény"
                        },
                        new
                        {
                            Id = "402c788a-5b4f-4d18-8224-f2df312d45ea",
                            Original = "Compost bin",
                            TopicId = "7b68a801-15f0-4ddc-a164-e43c83687f25",
                            Translation = "Komposztáló"
                        },
                        new
                        {
                            Id = "73f1457a-e0bc-4aad-b157-82196f4fdade",
                            Original = "Garden bench",
                            TopicId = "7b68a801-15f0-4ddc-a164-e43c83687f25",
                            Translation = "Kerti pad"
                        },
                        new
                        {
                            Id = "bec6de99-cdb0-45c8-9bbf-1bced1462095",
                            Original = "Garden gnome",
                            TopicId = "7b68a801-15f0-4ddc-a164-e43c83687f25",
                            Translation = "Kerti törpe"
                        });
                });

            modelBuilder.Entity("WordQuiz.Models.WordStatistic", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PlayerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<string>("WordId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("WordId");

                    b.ToTable("WordStatistics");
                });

            modelBuilder.Entity("WordQuiz.Models.Player", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Player");

                    b.HasData(
                        new
                        {
                            Id = "ef359a77-196a-4e0f-9216-1381ac4601d0",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "daa21a2a-a180-4287-9778-50c42cbfcf6f",
                            Email = "seedplayer@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedUserName = "SEEDPLAYER@gmail.com",
                            PasswordHash = "AQAAAAEAACcQAAAAEChObQYQWozWcptPpqiD+oY9vhA3ivnkXprSDL/hpMHaIx3ClPCqKGa3bgX5FlXlsA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "d1da9584-c36b-45c7-9b2d-54d0eae69f49",
                            TwoFactorEnabled = false,
                            UserName = "seedplayer@gmail.com",
                            PlayerName = "SeedPlayer"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WordQuiz.Models.Word", b =>
                {
                    b.HasOne("WordQuiz.Models.Topic", "Topic")
                        .WithMany("Words")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("WordQuiz.Models.WordStatistic", b =>
                {
                    b.HasOne("WordQuiz.Models.Player", "Player")
                        .WithMany("WordStatistics")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WordQuiz.Models.Word", "Word")
                        .WithMany()
                        .HasForeignKey("WordId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Word");
                });

            modelBuilder.Entity("WordQuiz.Models.Topic", b =>
                {
                    b.Navigation("Words");
                });

            modelBuilder.Entity("WordQuiz.Models.Player", b =>
                {
                    b.Navigation("WordStatistics");
                });
#pragma warning restore 612, 618
        }
    }
}
